#!/usr/bin/env python
"""
Moab-Condor compatibility layer

condor_status: return the list of all known machines in the Moab pool.

Usage
  condor_status OPTIONS

Options
  -long     verbose list
"""
import os
import time
import MOPS.Torque as Torque    




def status(long=False):
    if(long):
        TMPLT = 'Name = vm@%s'
    else:
        TMPLT = 'vm@%s'
    # <-- end if
    
    nodes = Torque.available()
    for node in nodes:
        print(TMPLT %(node))
    # <-- end for
    return(0)




if(__name__ == '__main__'):
    import optparse
    import sys
    


    # Constants
    USAGE = """Usage
  condor_status OPTIONS

Options
  -long     verbose list
"""


    # Hack. we want to support the condor_wait -wait and -num options, which
    # optparse does not support.
    for i in range(len(sys.argv[1:])):
        if(sys.argv[i+1][0] == '-' and
           sys.argv[i+1][1] != '-' and
           len(sys.argv[i+1]) > 1):
            sys.argv[i+1] = '-' + sys.argv[i+1]
        # <-- end if
    # <-- end for

    # Parse the command line input.
    parser = optparse.OptionParser(USAGE)
    parser.add_option('--long',
                      dest='long',
                      action='store_true',
                      default=False,
                      help='verose list')
    (options, args) = parser.parse_args()

    sys.exit(status(long))
# <-- end if
