# Makefile for dirlib ~/g/astroclean
# Created by jkubica on:  Tue Jan 17, 2006

here		= astroclean

includes	= astroclean.h astroclean_api.h

sources		= astroclean.c

private_sources = 

# Warning: Make sure the siblings are ordered so that, for example, if
#          a depends on b then b is to the right of a in the following list

siblings	= linkTracklets autonutils

t:=debug
include ../gmake-magic/Make.common

