/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.23
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */


#ifndef SWIG_TEMPLATE_DISAMBIGUATOR
#  if defined(__SUNPRO_CC) 
#    define SWIG_TEMPLATE_DISAMBIGUATOR template
#  else
#    define SWIG_TEMPLATE_DISAMBIGUATOR 
#  endif
#endif

/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#  if !defined(STATIC_LINKED)
#    define SWIGEXPORT(a) __declspec(dllexport) a
#  else
#    define SWIGEXPORT(a) a
#  endif
#else
#  define SWIGEXPORT(a) a
#endif

#define SWIGRUNTIME(x) static x

#ifndef SWIGINLINE
#if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#  define SWIGINLINE inline
#else
#  define SWIGINLINE
#endif
#endif


/* This should only be incremented when either the layout of swig_type_info changes,
   or for whatever reason, the runtime changes incompatibly */
#define SWIG_RUNTIME_VERSION "1"

/* define SWIG_TYPE_TABLE_NAME as "SWIG_TYPE_TABLE" */
#ifdef SWIG_TYPE_TABLE
#define SWIG_QUOTE_STRING(x) #x
#define SWIG_EXPAND_AND_QUOTE_STRING(x) SWIG_QUOTE_STRING(x)
#define SWIG_TYPE_TABLE_NAME SWIG_EXPAND_AND_QUOTE_STRING(SWIG_TYPE_TABLE)
#else
#define SWIG_TYPE_TABLE_NAME
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

static swig_type_info *swig_type_list = 0;
static swig_type_info **swig_type_list_handle = &swig_type_list;

/* 
   Compare two type names skipping the space characters, therefore
   "char*" == "char *" and "Class<int>" == "Class<int >", etc.

   Return 0 when the two name types are equivalent, as in
   strncmp, but skipping ' '.
*/
static int
SWIG_TypeNameComp(const char *f1, const char *l1,
		  const char *f2, const char *l2) {
  for (;(f1 != l1) && (f2 != l2); ++f1, ++f2) {
    while ((*f1 == ' ') && (f1 != l1)) ++f1;
    while ((*f2 == ' ') && (f2 != l2)) ++f2;
    if (*f1 != *f2) return *f1 - *f2;
  }
  return (l1 - f1) - (l2 - f2);
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
*/
static int
SWIG_TypeEquiv(const char *nb, const char *tb) {
  int equiv = 0;
  const char* te = tb + strlen(tb);
  const char* ne = nb;
  while (!equiv && *ne) {
    for (nb = ne; *ne; ++ne) {
      if (*ne == '|') break;
    }
    equiv = SWIG_TypeNameComp(nb, ne, tb, te) == 0;
    if (*ne) ++ne;
  }
  return equiv;
}
  

/* Register a type mapping with the type-checking */
static swig_type_info *
SWIG_TypeRegister(swig_type_info *ti) {
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = *swig_type_list_handle;
  while (tc) {
    /* check simple type equivalence */
    int typeequiv = (strcmp(tc->name, ti->name) == 0);   
    /* check full type equivalence, resolving typedefs */
    if (!typeequiv) {
      /* only if tc is not a typedef (no '|' on it) */
      if (tc->str && ti->str && !strstr(tc->str,"|")) {
	typeequiv = SWIG_TypeEquiv(ti->str,tc->str);
      }
    }
    if (typeequiv) {
      /* Already exists in the table.  Just add additional types to the list */
      if (ti->clientdata) tc->clientdata = ti->clientdata;
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = *swig_type_list_handle;
  *swig_type_list_handle = ti;

  /* Build linked lists */
  l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;
  head->next = next;

  return ret;
}

/* Check the typename */
static swig_type_info *
SWIG_TypeCheck(char *c, swig_type_info *ty) {
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
        s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Cast a pointer up an inheritance hierarchy */
static SWIGINLINE void *
SWIG_TypeCast(swig_type_info *ty, void *ptr) {
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Dynamic pointer casting. Down an inheritance hierarchy */
static swig_type_info *
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/* Return the name associated with this type */
static SWIGINLINE const char *
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/* Return the pretty name associated with this type,
   that is an unmangled type name in a form presentable to the user.
*/
static const char *
SWIG_TypePrettyName(const swig_type_info *type) {
  /* The "str" field contains the equivalent pretty names of the
     type, separated by vertical-bar characters.  We choose
     to print the last name, as it is often (?) the most
     specific. */
  if (type->str != NULL) {
    const char *last_name = type->str;
    const char *s;
    for (s = type->str; *s; s++)
      if (*s == '|') last_name = s+1;
    return last_name;
  }
  else
    return type->name;
}

/* Search for a swig_type_info structure */
static swig_type_info *
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = *swig_type_list_handle;
  while (ty) {
    if (ty->str && (SWIG_TypeEquiv(ty->str,name))) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
static void
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata) return;
  /* if (ti->clientdata == clientdata) return; */
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = *swig_type_list_handle;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0))
          SWIG_TypeClientData(tc,clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* Pack binary data into a string */
static char *
SWIG_PackData(char *c, void *ptr, size_t sz) {
  static char hex[17] = "0123456789abcdef";
  unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu =  u + sz;
  register unsigned char uu;
  for (; u != eu; ++u) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
static char *
SWIG_UnpackData(char *c, void *ptr, size_t sz) {
  register unsigned char uu = 0;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu =  u + sz;
  for (; u != eu; ++u) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

/* This function will propagate the clientdata field of type to
* any new swig_type_info structures that have been added into the list
* of equivalent types.  It is like calling
* SWIG_TypeClientData(type, clientdata) a second time.
*/
static void
SWIG_PropagateClientData(swig_type_info *type) {
  swig_type_info *equiv = type->next;
  swig_type_info *tc;
  if (!type->clientdata) return;
  while (equiv) {
    if (!equiv->converter) {
      tc = *swig_type_list_handle;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0) && !tc->clientdata)
          SWIG_TypeClientData(tc, type->clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

#ifdef __cplusplus
}
#endif

/* ---------------------------------------------------------------------- -*- c -*-
 * perl5.swg
 *
 * Perl5 runtime library
 * $Header$
 * ----------------------------------------------------------------------------- */

#define SWIGPERL
#define SWIGPERL5
#ifdef __cplusplus
/* Needed on some windows machines---since MS plays funny games with the header files under C++ */
#include <math.h>
#include <stdlib.h>
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

/* Get rid of free and malloc defined by perl */
#undef free
#undef malloc

#ifndef pTHX_
#define pTHX_
#endif

#include <string.h>
#ifdef __cplusplus
}
#endif

/* Macro to call an XS function */

#ifdef PERL_OBJECT 
#  define SWIG_CALLXS(_name) _name(cv,pPerl) 
#else 
#  ifndef MULTIPLICITY 
#    define SWIG_CALLXS(_name) _name(cv) 
#  else 
#    define SWIG_CALLXS(_name) _name(PERL_GET_THX, cv) 
#  endif 
#endif 

/* Contract support */

#define SWIG_contract_assert(expr,msg) if (!(expr)) { SWIG_croak(msg); } else

/* Note: SwigMagicFuncHack is a typedef used to get the C++ compiler to just shut up already */

#ifdef PERL_OBJECT
#define MAGIC_PPERL  CPerlObj *pPerl = (CPerlObj *) this;
typedef int (CPerlObj::*SwigMagicFunc)(SV *, MAGIC *);

#ifdef __cplusplus
extern "C" {
#endif
typedef int (CPerlObj::*SwigMagicFuncHack)(SV *, MAGIC *);
#ifdef __cplusplus
}
#endif

#define SWIG_MAGIC(a,b) (SV *a, MAGIC *b)
#define SWIGCLASS_STATIC
#else
#define MAGIC_PPERL
#define SWIGCLASS_STATIC static
#ifndef MULTIPLICITY
#define SWIG_MAGIC(a,b) (SV *a, MAGIC *b)
typedef int (*SwigMagicFunc)(SV *, MAGIC *);

#ifdef __cplusplus
extern "C" {
#endif
typedef int (*SwigMagicFuncHack)(SV *, MAGIC *);
#ifdef __cplusplus
}
#endif


#else
#define SWIG_MAGIC(a,b) (struct interpreter *interp, SV *a, MAGIC *b)
typedef int (*SwigMagicFunc)(struct interpreter *, SV *, MAGIC *);
#ifdef __cplusplus
extern "C" {
#endif
typedef int (*SwigMagicFuncHack)(struct interpreter *, SV *, MAGIC *);
#ifdef __cplusplus
}
#endif

#endif
#endif

#if defined(WIN32) && defined(PERL_OBJECT) && !defined(PerlIO_exportFILE)
#define PerlIO_exportFILE(fh,fl) (FILE*)(fh)
#endif

/* Modifications for newer Perl 5.005 releases */

#if !defined(PERL_REVISION) || ((PERL_REVISION >= 5) && ((PERL_VERSION < 5) || ((PERL_VERSION == 5) && (PERL_SUBVERSION < 50))))
#  ifndef PL_sv_yes
#    define PL_sv_yes sv_yes
#  endif
#  ifndef PL_sv_undef
#    define PL_sv_undef sv_undef
#  endif
#  ifndef PL_na
#    define PL_na na
#  endif
#endif

#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_OWNER 1
#define SWIG_SHADOW 2

/* Common SWIG API */

#ifdef PERL_OBJECT
#  define SWIG_ConvertPtr(obj, pp, type, flags) \
     SWIG_Perl_ConvertPtr(pPerl, obj, pp, type, flags)
#  define SWIG_NewPointerObj(p, type, flags) \
     SWIG_Perl_NewPointerObj(pPerl, p, type, flags)
#  define SWIG_MakePackedObj(sv, p, s, type)	\
     SWIG_Perl_MakePackedObj(pPerl, sv, p, s, type)
#  define SWIG_ConvertPacked(obj, p, s, type, flags) \
     SWIG_Perl_ConvertPacked(pPerl, obj, p, s, type, flags)

#else
#  define SWIG_ConvertPtr(obj, pp, type, flags) \
     SWIG_Perl_ConvertPtr(obj, pp, type, flags)
#  define SWIG_NewPointerObj(p, type, flags) \
     SWIG_Perl_NewPointerObj(p, type, flags)
#  define SWIG_MakePackedObj(sv, p, s, type)	\
     SWIG_Perl_MakePackedObj(sv, p, s, type )
#  define SWIG_ConvertPacked(obj, p, s, type, flags) \
     SWIG_Perl_ConvertPacked(obj, p, s, type, flags)
#endif

/* Perl-specific API */
#ifdef PERL_OBJECT
#  define SWIG_MakePtr(sv, ptr, type, flags) \
     SWIG_Perl_MakePtr(pPerl, sv, ptr, type, flags)
#  define SWIG_SetError(str) \
     SWIG_Perl_SetError(pPerl, str)
#else
#  define SWIG_MakePtr(sv, ptr, type, flags) \
     SWIG_Perl_MakePtr(sv, ptr, type, flags)
#  define SWIG_SetError(str) \
     SWIG_Perl_SetError(str)
#  define SWIG_SetErrorSV(str) \
     SWIG_Perl_SetErrorSV(str)
#endif

#define SWIG_SetErrorf SWIG_Perl_SetErrorf


#ifdef PERL_OBJECT
#  define SWIG_MAYBE_PERL_OBJECT CPerlObj *pPerl,
#else
#  define SWIG_MAYBE_PERL_OBJECT
#endif

/* load the swig_runtime_list_handle variable from the interpreter */
static void SWIG_Perl_LookupTypePointer() {
  SV *pointer;

  /* first check if pointer already created */
  pointer = get_sv("swig_runtime_data::type_pointer" SWIG_RUNTIME_VERSION SWIG_TYPE_TABLE_NAME, FALSE);
  if (pointer && SvOK(pointer)) {
    swig_type_list_handle = INT2PTR(swig_type_info **, SvIV(pointer));
  } else {
    /* create a new pointer */
    pointer = get_sv("swig_runtime_data::type_pointer" SWIG_RUNTIME_VERSION SWIG_TYPE_TABLE_NAME, TRUE);
    sv_setiv(pointer, PTR2IV(swig_type_list_handle));
  }
}

static swig_type_info *
SWIG_Perl_TypeCheckRV(SWIG_MAYBE_PERL_OBJECT SV *rv, swig_type_info *ty) {
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (sv_derived_from(rv, (char *) s->name)) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
        s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Function for getting a pointer value */

static int
SWIG_Perl_ConvertPtr(SWIG_MAYBE_PERL_OBJECT SV *sv, void **ptr, swig_type_info *_t, int flags) {
  swig_type_info *tc;
  void *voidptr = (void *)0;

  /* If magical, apply more magic */
  if (SvGMAGICAL(sv))
    mg_get(sv);

  /* Check to see if this is an object */
  if (sv_isobject(sv)) {
    SV *tsv = (SV*) SvRV(sv);
    IV tmp = 0;
    if ((SvTYPE(tsv) == SVt_PVHV)) {
      MAGIC *mg;
      if (SvMAGICAL(tsv)) {
        mg = mg_find(tsv,'P');
        if (mg) {
          sv = mg->mg_obj;
          if (sv_isobject(sv)) {
            tmp = SvIV((SV*)SvRV(sv));
          }
        }
      } else {
        return -1;
      }
    } else {
      tmp = SvIV((SV*)SvRV(sv));
    }
    voidptr = (void *)tmp;
    if (!_t) {
      *(ptr) = voidptr;
      return 0;
    }
  } else if (! SvOK(sv)) {            /* Check for undef */
    *(ptr) = (void *) 0;
    return 0;
  } else if (SvTYPE(sv) == SVt_RV) {  /* Check for NULL pointer */
    *(ptr) = (void *) 0;
    if (!SvROK(sv))
      return 0;
    else
      return -1;
  } else {                            /* Don't know what it is */
    *(ptr) = (void *) 0;
    return -1;
  }
  if (_t) {
    /* Now see if the types match */
    char *_c = HvNAME(SvSTASH(SvRV(sv)));
    tc = SWIG_TypeCheck(_c,_t);
    if (!tc) {
      *ptr = voidptr;
      return -1;
    }
    *ptr = SWIG_TypeCast(tc,voidptr);
    return 0;
  }
  *ptr = voidptr;
  return 0;
}

static void
SWIG_Perl_MakePtr(SWIG_MAYBE_PERL_OBJECT SV *sv, void *ptr, swig_type_info *t, int flags) {
  if (ptr && (flags & SWIG_SHADOW)) {
    SV *self;
    SV *obj=newSV(0);
    HV *hash=newHV();
    HV *stash;
    sv_setref_pv(obj, (char *) t->name, ptr);
    stash=SvSTASH(SvRV(obj));
    if (flags & SWIG_OWNER) {
      HV *hv;
      GV *gv=*(GV**)hv_fetch(stash, "OWNER", 5, TRUE);
      if (!isGV(gv))
        gv_init(gv, stash, "OWNER", 5, FALSE);
      hv=GvHVn(gv);
      hv_store_ent(hv, obj, newSViv(1), 0);
    }
    sv_magic((SV *)hash, (SV *)obj, 'P', Nullch, 0);
    SvREFCNT_dec(obj);
    self=newRV_noinc((SV *)hash);
    sv_setsv(sv, self);
    SvREFCNT_dec((SV *)self);
    sv_bless(sv, stash);
  }
  else {
    sv_setref_pv(sv, (char *) t->name, ptr);
  }
}

static SWIGINLINE SV *
SWIG_Perl_NewPointerObj(SWIG_MAYBE_PERL_OBJECT void *ptr, swig_type_info *t, int flags) {
  SV *result = sv_newmortal();
  SWIG_MakePtr(result, ptr, t, flags);
  return result;
}

static void
  SWIG_Perl_MakePackedObj(SWIG_MAYBE_PERL_OBJECT SV *sv, void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  sv_setpv(sv, result);
}

/* Convert a packed value value */
static int
SWIG_Perl_ConvertPacked(SWIG_MAYBE_PERL_OBJECT SV *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c = 0;

  if ((!obj) || (!SvOK(obj))) return -1;
  c = SvPV(obj, PL_na);
  /* Pointer values must start with leading underscore */
  if (*c != '_') return -1;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) return -1;
  }
  return 0;
}

static SWIGINLINE void
SWIG_Perl_SetError(SWIG_MAYBE_PERL_OBJECT const char *error) {
  if (error) sv_setpv(perl_get_sv("@", TRUE), error);
}

static SWIGINLINE void
SWIG_Perl_SetErrorSV(SWIG_MAYBE_PERL_OBJECT SV *error) {
  if (error) sv_setsv(perl_get_sv("@", TRUE), error);
}

static void
SWIG_Perl_SetErrorf(const char *fmt, ...) {
  va_list args;
  va_start(args, fmt);
  sv_vsetpvfn(perl_get_sv("@", TRUE), fmt, strlen(fmt), &args, Null(SV**), 0, Null(bool*));
  va_end(args);
}

/* Macros for low-level exception handling */
#define SWIG_fail       goto fail
#define SWIG_croak(x)   { SWIG_SetError(x); goto fail; }
#define SWIG_croakSV(x) { SWIG_SetErrorSV(x); goto fail; }
/* most preprocessors do not support vararg macros :-( */
/* #define SWIG_croakf(x...) { SWIG_SetErrorf(x); goto fail; } */


typedef XS(SwigPerlWrapper);
typedef SwigPerlWrapper *SwigPerlWrapperPtr;

/* Structure for command table */
typedef struct {
  const char         *name;
  SwigPerlWrapperPtr  wrapper;
} swig_command_info;

/* Information for constant table */

#define SWIG_INT     1
#define SWIG_FLOAT   2
#define SWIG_STRING  3
#define SWIG_POINTER 4
#define SWIG_BINARY  5

/* Constant information structure */
typedef struct swig_constant_info {
    int              type;
    const char      *name;
    long             lvalue;
    double           dvalue;
    void            *pvalue;
    swig_type_info **ptype;
} swig_constant_info;

#ifdef __cplusplus
}
#endif

/* Structure for variable table */
typedef struct {
  const char   *name;
  SwigMagicFunc   set;
  SwigMagicFunc   get;
  swig_type_info  **type;
} swig_variable_info;

/* Magic variable code */
#ifndef PERL_OBJECT
#define swig_create_magic(s,a,b,c) _swig_create_magic(s,a,b,c)
  #ifndef MULTIPLICITY
     static void _swig_create_magic(SV *sv, char *name, int (*set)(SV *, MAGIC *), int (*get)(SV *,MAGIC *)) {
  #else
     static void _swig_create_magic(SV *sv, char *name, int (*set)(struct interpreter*, SV *, MAGIC *), int (*get)(struct interpreter*, SV *,MAGIC *)) {
  #endif
#else
#  define swig_create_magic(s,a,b,c) _swig_create_magic(pPerl,s,a,b,c)
static void _swig_create_magic(CPerlObj *pPerl, SV *sv, const char *name, int (CPerlObj::*set)(SV *, MAGIC *), int (CPerlObj::*get)(SV *, MAGIC *)) {
#endif
  MAGIC *mg;
  sv_magic(sv,sv,'U',(char *) name,strlen(name));
  mg = mg_find(sv,'U');
  mg->mg_virtual = (MGVTBL *) malloc(sizeof(MGVTBL));
  mg->mg_virtual->svt_get = (SwigMagicFuncHack) get;
  mg->mg_virtual->svt_set = (SwigMagicFuncHack) set;
  mg->mg_virtual->svt_len = 0;
  mg->mg_virtual->svt_clear = 0;
  mg->mg_virtual->svt_free = 0;
}






#ifdef do_open
  #undef do_open
#endif
#ifdef do_close
  #undef do_close
#endif
#ifdef scalar
  #undef scalar
#endif
#ifdef list
  #undef list
#endif
#ifdef apply
  #undef apply
#endif
#ifdef convert
  #undef convert
#endif
#ifdef Error
  #undef Error
#endif
#ifdef form
  #undef form
#endif
#ifdef vform
  #undef vform
#endif
#ifdef LABEL
  #undef LABEL
#endif
#ifdef METHOD
  #undef METHOD
#endif
#ifdef Move
  #undef Move
#endif
#ifdef yylex
  #undef yylex
#endif
#ifdef yyparse
  #undef yyparse
#endif
#ifdef yyerror
  #undef yyerror
#endif
#ifdef invert
  #undef invert
#endif
#ifdef ref
  #undef ref
#endif
#ifdef ENTER
  #undef ENTER
#endif


/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_StringTP swig_types[0] 
#define  SWIGTYPE_p_OrbitTP swig_types[1] 
#define  SWIGTYPE_p_ModcOrbitTP swig_types[2] 
#define  SWIGTYPE_p_ModcDetArrayTP swig_types[3] 
#define  SWIGTYPE_DoubleArrayTP swig_types[4] 
#define  SWIGTYPE_p_OrbitArrayTP swig_types[5] 
#define  SWIGTYPE_p_ModcOrbitArrayTP swig_types[6] 
#define  SWIGTYPE_p_double swig_types[7] 
#define  SWIGTYPE_p_SucceedTP swig_types[8] 
#define  SWIGTYPE_p_CovMatrixTP swig_types[9] 
#define  SWIGTYPE_p_IdTP swig_types[10] 
#define  SWIGTYPE_p_time_t swig_types[11] 
#define  SWIGTYPE_p_BoolTP swig_types[12] 
#define  SWIGTYPE_p_FlagTP swig_types[13] 
#define  SWIGTYPE_p_MjdTP swig_types[14] 
#define  SWIGTYPE_p_ModcDetTP swig_types[15] 
#define  SWIGTYPE_p_TaxonomicTP swig_types[16] 
static swig_type_info *swig_types[18];

/* -------- TYPES TABLE (END) -------- */

#define SWIG_init    boot_PS__MOPS__DB__Orbit

#define SWIG_name   "PS::MOPS::DB::Orbitc::boot_PS__MOPS__DB__Orbit"
#define SWIG_prefix "PS::MOPS::DB::Orbitc::"

#ifdef __cplusplus
extern "C"
#endif
#ifndef PERL_OBJECT
#ifndef MULTIPLICITY
SWIGEXPORT(void) SWIG_init (CV* cv);
#else
SWIGEXPORT(void) SWIG_init (pTHXo_ CV* cv);
#endif
#else
SWIGEXPORT(void) SWIG_init (CV *cv, CPerlObj *);
#endif


static double *new_doubleArray(int nelements) { 
  return (double *) calloc(nelements,sizeof(double)); 
}

static void delete_doubleArray(double *ary) { 
  free(ary); 
}

static double doubleArray_getitem(double *ary, int index) {
    return ary[index];
}
static void doubleArray_setitem(double *ary, int index, double value) {
    ary[index] = value;
}


#include "modc.h"

#ifdef PERL_OBJECT
#define MAGIC_CLASS _wrap_PS::MOPS::DB::Orbit_var::
class _wrap_PS::MOPS::DB::Orbit_var : public CPerlObj {
public:
#else
#define MAGIC_CLASS
#endif
SWIGCLASS_STATIC int swig_magic_readonly(pTHX_ SV *sv, MAGIC *mg) {
    MAGIC_PPERL
    sv = sv; mg = mg;
    croak("Value is read-only.");
    return 0;
}


#ifdef PERL_OBJECT
};
#endif

#ifdef __cplusplus
extern "C" {
#endif
XS(_wrap_new_doubleArray) {
    {
        int arg1 ;
        double *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: new_doubleArray(nelements);");
        }
        arg1 = (int) SvIV(ST(0));
        result = (double *)new_doubleArray(arg1);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_double, 0|0);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_delete_doubleArray) {
    {
        double *arg1 = (double *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: delete_doubleArray(ary);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_double,0) < 0) {
                SWIG_croak("Type error in argument 1 of delete_doubleArray. Expected _p_double");
            }
        }
        delete_doubleArray(arg1);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_doubleArray_getitem) {
    {
        double *arg1 = (double *) 0 ;
        int arg2 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: doubleArray_getitem(ary,index);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_double,0) < 0) {
                SWIG_croak("Type error in argument 1 of doubleArray_getitem. Expected _p_double");
            }
        }
        arg2 = (int) SvIV(ST(1));
        result = (double)doubleArray_getitem(arg1,arg2);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_doubleArray_setitem) {
    {
        double *arg1 = (double *) 0 ;
        int arg2 ;
        double arg3 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 3) || (items > 3)) {
            SWIG_croak("Usage: doubleArray_setitem(ary,index,value);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_double,0) < 0) {
                SWIG_croak("Type error in argument 1 of doubleArray_setitem. Expected _p_double");
            }
        }
        arg2 = (int) SvIV(ST(1));
        arg3 = (double) SvNV(ST(2));
        
        doubleArray_setitem(arg1,arg2,arg3);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_toStruct) {
    {
        ModcOrbitTP arg1 ;
        OrbitTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_toStruct(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_toStruct. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = modco_toStruct(arg1);
        
        {
            OrbitTP * resultobj = (OrbitTP *) malloc(sizeof(OrbitTP));
            memmove(resultobj, &result, sizeof(OrbitTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_OrbitTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_toStructArray) {
    {
        ModcOrbitTP arg1 ;
        OrbitArrayTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_toStructArray(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_toStructArray. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = modco_toStructArray(arg1);
        
        {
            OrbitArrayTP * resultobj = (OrbitArrayTP *) malloc(sizeof(OrbitArrayTP));
            memmove(resultobj, &result, sizeof(OrbitArrayTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_OrbitArrayTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getCount) {
    {
        ModcOrbitTP arg1 ;
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getCount(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getCount. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (int)modco_getCount(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_create) {
    {
        double arg1 ;
        double arg2 ;
        double arg3 ;
        double arg4 ;
        double arg5 ;
        MjdTP arg6 ;
        MjdTP arg7 ;
        double arg8 ;
        double arg9 ;
        BoolTP arg10 ;
        int arg11 ;
        CovMatrixTP arg12 ;
        DoubleArrayTP arg13 = (DoubleArrayTP) 0 ;
        DoubleArrayTP arg14 = (DoubleArrayTP) 0 ;
        StringTP arg15 ;
        TaxonomicTP arg16 ;
        double arg17 ;
        double arg18 ;
        MjdTP arg19 ;
        double arg20 ;
        double arg21 ;
        double arg22 ;
        double arg23 ;
        double arg24 ;
        double arg25 ;
        ModcOrbitTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 25) || (items > 25)) {
            SWIG_croak("Usage: modco_create(q,e,i,node,longPeri,timePeri,epoch,chiSquared,oMinusC,isFake,orbitFlags,covMatrix,moid,moidLong,objectName,taxonomicType,rotationPeriod,amplitude,rotationEpoch,hV,hSS,g,albedo,poleLat,poleLong);");
        }
        arg1 = (double) SvNV(ST(0));
        
        arg2 = (double) SvNV(ST(1));
        
        arg3 = (double) SvNV(ST(2));
        
        arg4 = (double) SvNV(ST(3));
        
        arg5 = (double) SvNV(ST(4));
        
        arg6 = (MjdTP) SvNV(ST(5));
        
        arg7 = (MjdTP) SvNV(ST(6));
        
        arg8 = (double) SvNV(ST(7));
        
        arg9 = (double) SvNV(ST(8));
        
        arg10 = (BoolTP) SvIV(ST(9));
        arg11 = (int) SvIV(ST(10));
        {
            CovMatrixTP * argp;
            if (SWIG_ConvertPtr(ST(11),(void **) &argp, SWIGTYPE_p_CovMatrixTP,0) < 0) {
                SWIG_croak("Type error in argument 12 of modco_create. Expected _p_CovMatrixTP");
            }
            arg12 = *argp;
        }
        {
            if (SWIG_ConvertPtr(ST(12), (void **) &arg13, SWIGTYPE_DoubleArrayTP,0) < 0) {
                SWIG_croak("Type error in argument 13 of modco_create. Expected _DoubleArrayTP");
            }
        }
        {
            if (SWIG_ConvertPtr(ST(13), (void **) &arg14, SWIGTYPE_DoubleArrayTP,0) < 0) {
                SWIG_croak("Type error in argument 14 of modco_create. Expected _DoubleArrayTP");
            }
        }
        {
            StringTP * argp;
            if (SWIG_ConvertPtr(ST(14),(void **) &argp, SWIGTYPE_p_StringTP,0) < 0) {
                SWIG_croak("Type error in argument 15 of modco_create. Expected _p_StringTP");
            }
            arg15 = *argp;
        }
        {
            TaxonomicTP * argp;
            if (SWIG_ConvertPtr(ST(15),(void **) &argp, SWIGTYPE_p_TaxonomicTP,0) < 0) {
                SWIG_croak("Type error in argument 16 of modco_create. Expected _p_TaxonomicTP");
            }
            arg16 = *argp;
        }
        arg17 = (double) SvNV(ST(16));
        
        arg18 = (double) SvNV(ST(17));
        
        arg19 = (MjdTP) SvNV(ST(18));
        
        arg20 = (double) SvNV(ST(19));
        
        arg21 = (double) SvNV(ST(20));
        
        arg22 = (double) SvNV(ST(21));
        
        arg23 = (double) SvNV(ST(22));
        
        arg24 = (double) SvNV(ST(23));
        
        arg25 = (double) SvNV(ST(24));
        
        result = modco_create(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13,arg14,arg15,arg16,arg17,arg18,arg19,arg20,arg21,arg22,arg23,arg24,arg25);
        
        {
            ModcOrbitTP * resultobj = (ModcOrbitTP *) malloc(sizeof(ModcOrbitTP));
            memmove(resultobj, &result, sizeof(ModcOrbitTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcOrbitTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_retrieve) {
    {
        IdTP arg1 ;
        ModcOrbitTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_retrieve(orbId);");
        }
        arg1 = (IdTP) SvIV(ST(0));
        result = modco_retrieve(arg1);
        
        {
            ModcOrbitTP * resultobj = (ModcOrbitTP *) malloc(sizeof(ModcOrbitTP));
            memmove(resultobj, &result, sizeof(ModcOrbitTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcOrbitTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_retrieveByValue) {
    {
        double arg1 ;
        double arg2 ;
        double arg3 ;
        double arg4 ;
        double arg5 ;
        double arg6 ;
        double arg7 ;
        double arg8 ;
        double arg9 ;
        double arg10 ;
        double arg11 ;
        double arg12 ;
        double arg13 ;
        double arg14 ;
        BoolTP arg15 ;
        ModcOrbitTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 15) || (items > 15)) {
            SWIG_croak("Usage: modco_retrieveByValue(q,e,i,node,longPeri,timePeri,epoch,deltaQ,deltaE,deltaI,deltaNode,deltaLongPeri,deltaTimePeri,deltaEpoch,isFake);");
        }
        arg1 = (double) SvNV(ST(0));
        
        arg2 = (double) SvNV(ST(1));
        
        arg3 = (double) SvNV(ST(2));
        
        arg4 = (double) SvNV(ST(3));
        
        arg5 = (double) SvNV(ST(4));
        
        arg6 = (double) SvNV(ST(5));
        
        arg7 = (double) SvNV(ST(6));
        
        arg8 = (double) SvNV(ST(7));
        
        arg9 = (double) SvNV(ST(8));
        
        arg10 = (double) SvNV(ST(9));
        
        arg11 = (double) SvNV(ST(10));
        
        arg12 = (double) SvNV(ST(11));
        
        arg13 = (double) SvNV(ST(12));
        
        arg14 = (double) SvNV(ST(13));
        
        arg15 = (BoolTP) SvIV(ST(14));
        result = modco_retrieveByValue(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13,arg14,arg15);
        
        {
            ModcOrbitTP * resultobj = (ModcOrbitTP *) malloc(sizeof(ModcOrbitTP));
            memmove(resultobj, &result, sizeof(ModcOrbitTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcOrbitTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_retrieveByDetectionId) {
    {
        IdTP arg1 ;
        ModcOrbitTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_retrieveByDetectionId(detId);");
        }
        arg1 = (IdTP) SvIV(ST(0));
        result = modco_retrieveByDetectionId(arg1);
        
        {
            ModcOrbitTP * resultobj = (ModcOrbitTP *) malloc(sizeof(ModcOrbitTP));
            memmove(resultobj, &result, sizeof(ModcOrbitTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcOrbitTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_insertByValue) {
    {
        double arg1 ;
        double arg2 ;
        double arg3 ;
        double arg4 ;
        double arg5 ;
        MjdTP arg6 ;
        MjdTP arg7 ;
        double arg8 ;
        double arg9 ;
        BoolTP arg10 ;
        FlagTP arg11 ;
        CovMatrixTP arg12 ;
        DoubleArrayTP arg13 = (DoubleArrayTP) 0 ;
        DoubleArrayTP arg14 = (DoubleArrayTP) 0 ;
        StringTP arg15 ;
        TaxonomicTP arg16 ;
        double arg17 ;
        double arg18 ;
        MjdTP arg19 ;
        double arg20 ;
        double arg21 ;
        double arg22 ;
        double arg23 ;
        double arg24 ;
        double arg25 ;
        ModcOrbitTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 25) || (items > 25)) {
            SWIG_croak("Usage: modco_insertByValue(q,e,i,node,longPeri,timePeri,epoch,chiSquared,oMinusC,isFake,orbitFlags,covMatrix,moid,moidLong,objectName,taxonomicType,rotationPeriod,amplitude,rotationEpoch,hV,hSS,g,albedo,poleLat,poleLong);");
        }
        arg1 = (double) SvNV(ST(0));
        
        arg2 = (double) SvNV(ST(1));
        
        arg3 = (double) SvNV(ST(2));
        
        arg4 = (double) SvNV(ST(3));
        
        arg5 = (double) SvNV(ST(4));
        
        arg6 = (MjdTP) SvNV(ST(5));
        
        arg7 = (MjdTP) SvNV(ST(6));
        
        arg8 = (double) SvNV(ST(7));
        
        arg9 = (double) SvNV(ST(8));
        
        arg10 = (BoolTP) SvIV(ST(9));
        arg11 = (FlagTP) SvIV(ST(10));
        {
            CovMatrixTP * argp;
            if (SWIG_ConvertPtr(ST(11),(void **) &argp, SWIGTYPE_p_CovMatrixTP,0) < 0) {
                SWIG_croak("Type error in argument 12 of modco_insertByValue. Expected _p_CovMatrixTP");
            }
            arg12 = *argp;
        }
        {
            if (SWIG_ConvertPtr(ST(12), (void **) &arg13, SWIGTYPE_DoubleArrayTP,0) < 0) {
                SWIG_croak("Type error in argument 13 of modco_insertByValue. Expected _DoubleArrayTP");
            }
        }
        {
            if (SWIG_ConvertPtr(ST(13), (void **) &arg14, SWIGTYPE_DoubleArrayTP,0) < 0) {
                SWIG_croak("Type error in argument 14 of modco_insertByValue. Expected _DoubleArrayTP");
            }
        }
        {
            StringTP * argp;
            if (SWIG_ConvertPtr(ST(14),(void **) &argp, SWIGTYPE_p_StringTP,0) < 0) {
                SWIG_croak("Type error in argument 15 of modco_insertByValue. Expected _p_StringTP");
            }
            arg15 = *argp;
        }
        {
            TaxonomicTP * argp;
            if (SWIG_ConvertPtr(ST(15),(void **) &argp, SWIGTYPE_p_TaxonomicTP,0) < 0) {
                SWIG_croak("Type error in argument 16 of modco_insertByValue. Expected _p_TaxonomicTP");
            }
            arg16 = *argp;
        }
        arg17 = (double) SvNV(ST(16));
        
        arg18 = (double) SvNV(ST(17));
        
        arg19 = (MjdTP) SvNV(ST(18));
        
        arg20 = (double) SvNV(ST(19));
        
        arg21 = (double) SvNV(ST(20));
        
        arg22 = (double) SvNV(ST(21));
        
        arg23 = (double) SvNV(ST(22));
        
        arg24 = (double) SvNV(ST(23));
        
        arg25 = (double) SvNV(ST(24));
        
        result = modco_insertByValue(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13,arg14,arg15,arg16,arg17,arg18,arg19,arg20,arg21,arg22,arg23,arg24,arg25);
        
        {
            ModcOrbitTP * resultobj = (ModcOrbitTP *) malloc(sizeof(ModcOrbitTP));
            memmove(resultobj, &result, sizeof(ModcOrbitTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcOrbitTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_insert) {
    {
        ModcOrbitTP arg1 ;
        SucceedTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_insert(orbit);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_insert. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = modco_insert(arg1);
        
        {
            SucceedTP * resultobj = (SucceedTP *) malloc(sizeof(SucceedTP));
            memmove(resultobj, &result, sizeof(SucceedTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_SucceedTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_attributeDetections) {
    {
        ModcOrbitTP arg1 ;
        ModcDetArrayTP arg2 ;
        SucceedTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: modco_attributeDetections(orbit,dets);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_attributeDetections. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        {
            ModcDetArrayTP * argp;
            if (SWIG_ConvertPtr(ST(1),(void **) &argp, SWIGTYPE_p_ModcDetArrayTP,0) < 0) {
                SWIG_croak("Type error in argument 2 of modco_attributeDetections. Expected _p_ModcDetArrayTP");
            }
            arg2 = *argp;
        }
        result = modco_attributeDetections(arg1,arg2);
        
        {
            SucceedTP * resultobj = (SucceedTP *) malloc(sizeof(SucceedTP));
            memmove(resultobj, &result, sizeof(SucceedTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_SucceedTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_clearDetections) {
    {
        ModcOrbitTP arg1 ;
        ModcDetArrayTP arg2 ;
        SucceedTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: modco_clearDetections(orb,dets);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_clearDetections. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        {
            ModcDetArrayTP * argp;
            if (SWIG_ConvertPtr(ST(1),(void **) &argp, SWIGTYPE_p_ModcDetArrayTP,0) < 0) {
                SWIG_croak("Type error in argument 2 of modco_clearDetections. Expected _p_ModcDetArrayTP");
            }
            arg2 = *argp;
        }
        result = modco_clearDetections(arg1,arg2);
        
        {
            SucceedTP * resultobj = (SucceedTP *) malloc(sizeof(SucceedTP));
            memmove(resultobj, &result, sizeof(SucceedTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_SucceedTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_update) {
    {
        ModcOrbitTP arg1 ;
        double arg2 ;
        double arg3 ;
        double arg4 ;
        double arg5 ;
        double arg6 ;
        MjdTP arg7 ;
        MjdTP arg8 ;
        double arg9 ;
        double arg10 ;
        BoolTP arg11 ;
        FlagTP arg12 ;
        CovMatrixTP arg13 ;
        DoubleArrayTP arg14 = (DoubleArrayTP) 0 ;
        DoubleArrayTP arg15 = (DoubleArrayTP) 0 ;
        StringTP arg16 ;
        TaxonomicTP arg17 ;
        double arg18 ;
        double arg19 ;
        MjdTP arg20 ;
        double arg21 ;
        double arg22 ;
        double arg23 ;
        double arg24 ;
        double arg25 ;
        double arg26 ;
        SucceedTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 26) || (items > 26)) {
            SWIG_croak("Usage: modco_update(ptr,q,e,i,node,longPeri,timePeri,epoch,chiSquared,oMinusC,isFake,orbitFlags,covMatrix,moid,moidLong,objectName,taxonomicType,rotationPeriod,amplitude,rotationEpoch,hV,hSS,g,albedo,poleLat,poleLong);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_update. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        arg2 = (double) SvNV(ST(1));
        
        arg3 = (double) SvNV(ST(2));
        
        arg4 = (double) SvNV(ST(3));
        
        arg5 = (double) SvNV(ST(4));
        
        arg6 = (double) SvNV(ST(5));
        
        arg7 = (MjdTP) SvNV(ST(6));
        
        arg8 = (MjdTP) SvNV(ST(7));
        
        arg9 = (double) SvNV(ST(8));
        
        arg10 = (double) SvNV(ST(9));
        
        arg11 = (BoolTP) SvIV(ST(10));
        arg12 = (FlagTP) SvIV(ST(11));
        {
            CovMatrixTP * argp;
            if (SWIG_ConvertPtr(ST(12),(void **) &argp, SWIGTYPE_p_CovMatrixTP,0) < 0) {
                SWIG_croak("Type error in argument 13 of modco_update. Expected _p_CovMatrixTP");
            }
            arg13 = *argp;
        }
        {
            if (SWIG_ConvertPtr(ST(13), (void **) &arg14, SWIGTYPE_DoubleArrayTP,0) < 0) {
                SWIG_croak("Type error in argument 14 of modco_update. Expected _DoubleArrayTP");
            }
        }
        {
            if (SWIG_ConvertPtr(ST(14), (void **) &arg15, SWIGTYPE_DoubleArrayTP,0) < 0) {
                SWIG_croak("Type error in argument 15 of modco_update. Expected _DoubleArrayTP");
            }
        }
        {
            StringTP * argp;
            if (SWIG_ConvertPtr(ST(15),(void **) &argp, SWIGTYPE_p_StringTP,0) < 0) {
                SWIG_croak("Type error in argument 16 of modco_update. Expected _p_StringTP");
            }
            arg16 = *argp;
        }
        {
            TaxonomicTP * argp;
            if (SWIG_ConvertPtr(ST(16),(void **) &argp, SWIGTYPE_p_TaxonomicTP,0) < 0) {
                SWIG_croak("Type error in argument 17 of modco_update. Expected _p_TaxonomicTP");
            }
            arg17 = *argp;
        }
        arg18 = (double) SvNV(ST(17));
        
        arg19 = (double) SvNV(ST(18));
        
        arg20 = (MjdTP) SvNV(ST(19));
        
        arg21 = (double) SvNV(ST(20));
        
        arg22 = (double) SvNV(ST(21));
        
        arg23 = (double) SvNV(ST(22));
        
        arg24 = (double) SvNV(ST(23));
        
        arg25 = (double) SvNV(ST(24));
        
        arg26 = (double) SvNV(ST(25));
        
        result = modco_update(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13,arg14,arg15,arg16,arg17,arg18,arg19,arg20,arg21,arg22,arg23,arg24,arg25,arg26);
        
        {
            SucceedTP * resultobj = (SucceedTP *) malloc(sizeof(SucceedTP));
            memmove(resultobj, &result, sizeof(SucceedTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_SucceedTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_delete) {
    {
        IdTP arg1 ;
        SucceedTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_delete(orbitId);");
        }
        arg1 = (IdTP) SvIV(ST(0));
        result = modco_delete(arg1);
        
        {
            SucceedTP * resultobj = (SucceedTP *) malloc(sizeof(SucceedTP));
            memmove(resultobj, &result, sizeof(SucceedTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_SucceedTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_free) {
    {
        ModcOrbitTP arg1 ;
        SucceedTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_free(orbit);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_free. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = modco_free(arg1);
        
        {
            SucceedTP * resultobj = (SucceedTP *) malloc(sizeof(SucceedTP));
            memmove(resultobj, &result, sizeof(SucceedTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_SucceedTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_freeArray) {
    {
        ModcOrbitArrayTP arg1 ;
        SucceedTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_freeArray(orbits);");
        }
        {
            ModcOrbitArrayTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitArrayTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_freeArray. Expected _p_ModcOrbitArrayTP");
            }
            arg1 = *argp;
        }
        result = modco_freeArray(arg1);
        
        {
            SucceedTP * resultobj = (SucceedTP *) malloc(sizeof(SucceedTP));
            memmove(resultobj, &result, sizeof(SucceedTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_SucceedTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_freeStruct) {
    {
        OrbitTP arg1 ;
        SucceedTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_freeStruct(orbit);");
        }
        {
            OrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_OrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_freeStruct. Expected _p_OrbitTP");
            }
            arg1 = *argp;
        }
        result = modco_freeStruct(arg1);
        
        {
            SucceedTP * resultobj = (SucceedTP *) malloc(sizeof(SucceedTP));
            memmove(resultobj, &result, sizeof(SucceedTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_SucceedTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_freeArrayStruct) {
    {
        OrbitArrayTP arg1 ;
        SucceedTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_freeArrayStruct(orbits);");
        }
        {
            OrbitArrayTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_OrbitArrayTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_freeArrayStruct. Expected _p_OrbitArrayTP");
            }
            arg1 = *argp;
        }
        result = modco_freeArrayStruct(arg1);
        
        {
            SucceedTP * resultobj = (SucceedTP *) malloc(sizeof(SucceedTP));
            memmove(resultobj, &result, sizeof(SucceedTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_SucceedTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getId) {
    {
        ModcOrbitTP arg1 ;
        IdTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getId(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getId. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (IdTP)modco_getId(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getQ) {
    {
        ModcOrbitTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getQ(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getQ. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (double)modco_getQ(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getE) {
    {
        ModcOrbitTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getE(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getE. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (double)modco_getE(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getI) {
    {
        ModcOrbitTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getI(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getI. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (double)modco_getI(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getNode) {
    {
        ModcOrbitTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getNode(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getNode. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (double)modco_getNode(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getLongPeri) {
    {
        ModcOrbitTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getLongPeri(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getLongPeri. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (double)modco_getLongPeri(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getTimePeri) {
    {
        ModcOrbitTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getTimePeri(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getTimePeri. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (double)modco_getTimePeri(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getEpoch) {
    {
        ModcOrbitTP arg1 ;
        MjdTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getEpoch(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getEpoch. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (MjdTP)modco_getEpoch(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getDetCount) {
    {
        ModcOrbitTP arg1 ;
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getDetCount(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getDetCount. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (int)modco_getDetCount(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getChiSquared) {
    {
        ModcOrbitTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getChiSquared(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getChiSquared. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (double)modco_getChiSquared(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getOMinusC) {
    {
        ModcOrbitTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getOMinusC(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getOMinusC. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (double)modco_getOMinusC(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getIsFake) {
    {
        ModcOrbitTP arg1 ;
        BoolTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getIsFake(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getIsFake. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (BoolTP)modco_getIsFake(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getFlags) {
    {
        ModcOrbitTP arg1 ;
        FlagTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getFlags(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getFlags. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (FlagTP)modco_getFlags(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getUpdated) {
    {
        ModcOrbitTP arg1 ;
        time_t result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getUpdated(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getUpdated. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = modco_getUpdated(arg1);
        
        {
            time_t * resultobj = (time_t *) malloc(sizeof(time_t));
            memmove(resultobj, &result, sizeof(time_t));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_time_t, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getMoid) {
    {
        ModcOrbitTP arg1 ;
        DoubleArrayTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getMoid(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getMoid. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (DoubleArrayTP)modco_getMoid(arg1);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_DoubleArrayTP, 0|SWIG_OWNER);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getMoidLong) {
    {
        ModcOrbitTP arg1 ;
        DoubleArrayTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getMoidLong(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getMoidLong. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (DoubleArrayTP)modco_getMoidLong(arg1);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_DoubleArrayTP, 0|SWIG_OWNER);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getObjectName) {
    {
        ModcOrbitTP arg1 ;
        StringTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getObjectName(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getObjectName. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = modco_getObjectName(arg1);
        
        {
            StringTP * resultobj = (StringTP *) malloc(sizeof(StringTP));
            memmove(resultobj, &result, sizeof(StringTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_StringTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getTaxonomicType) {
    {
        ModcOrbitTP arg1 ;
        TaxonomicTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getTaxonomicType(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getTaxonomicType. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = modco_getTaxonomicType(arg1);
        
        {
            TaxonomicTP * resultobj = (TaxonomicTP *) malloc(sizeof(TaxonomicTP));
            memmove(resultobj, &result, sizeof(TaxonomicTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_TaxonomicTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getRotationPeriod) {
    {
        ModcOrbitTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getRotationPeriod(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getRotationPeriod. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (double)modco_getRotationPeriod(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getAmplitude) {
    {
        ModcOrbitTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getAmplitude(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getAmplitude. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (double)modco_getAmplitude(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getRotationEpoch) {
    {
        ModcOrbitTP arg1 ;
        MjdTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getRotationEpoch(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getRotationEpoch. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (MjdTP)modco_getRotationEpoch(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getHV) {
    {
        ModcOrbitTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getHV(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getHV. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (double)modco_getHV(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getHSS) {
    {
        ModcOrbitTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getHSS(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getHSS. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (double)modco_getHSS(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getG) {
    {
        ModcOrbitTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getG(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getG. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (double)modco_getG(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getAlbedo) {
    {
        ModcOrbitTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getAlbedo(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getAlbedo. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (double)modco_getAlbedo(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getPoleLat) {
    {
        ModcOrbitTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getPoleLat(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getPoleLat. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (double)modco_getPoleLat(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getPoleLong) {
    {
        ModcOrbitTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getPoleLong(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getPoleLong. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = (double)modco_getPoleLong(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_getDetections) {
    {
        ModcOrbitTP arg1 ;
        ModcDetArrayTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_getDetections(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_getDetections. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = modco_getDetections(arg1);
        
        {
            ModcDetArrayTP * resultobj = (ModcDetArrayTP *) malloc(sizeof(ModcDetArrayTP));
            memmove(resultobj, &result, sizeof(ModcDetArrayTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcDetArrayTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_next) {
    {
        ModcOrbitTP arg1 ;
        ModcOrbitTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_next(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_next. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = modco_next(arg1);
        
        {
            ModcOrbitTP * resultobj = (ModcOrbitTP *) malloc(sizeof(ModcOrbitTP));
            memmove(resultobj, &result, sizeof(ModcOrbitTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcOrbitTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_prev) {
    {
        ModcOrbitTP arg1 ;
        ModcOrbitTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_prev(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_prev. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = modco_prev(arg1);
        
        {
            ModcOrbitTP * resultobj = (ModcOrbitTP *) malloc(sizeof(ModcOrbitTP));
            memmove(resultobj, &result, sizeof(ModcOrbitTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcOrbitTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_nextDetection) {
    {
        ModcOrbitTP arg1 ;
        ModcDetTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_nextDetection(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_nextDetection. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = modco_nextDetection(arg1);
        
        {
            ModcDetTP * resultobj = (ModcDetTP *) malloc(sizeof(ModcDetTP));
            memmove(resultobj, &result, sizeof(ModcDetTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcDetTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modco_prevDetection) {
    {
        ModcOrbitTP arg1 ;
        ModcDetTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modco_prevDetection(ptr);");
        }
        {
            ModcOrbitTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcOrbitTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modco_prevDetection. Expected _p_ModcOrbitTP");
            }
            arg1 = *argp;
        }
        result = modco_prevDetection(arg1);
        
        {
            ModcDetTP * resultobj = (ModcDetTP *) malloc(sizeof(ModcDetTP));
            memmove(resultobj, &result, sizeof(ModcDetTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcDetTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}



/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_StringTP[] = {{"_p_StringTP", 0, "StringTP *", 0, 0, 0, 0},{"_p_StringTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_OrbitTP[] = {{"_p_OrbitTP", 0, "OrbitTP *", 0, 0, 0, 0},{"_p_OrbitTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_ModcOrbitTP[] = {{"_p_ModcOrbitTP", 0, "ModcOrbitTP *", 0, 0, 0, 0},{"_p_ModcOrbitTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_ModcDetArrayTP[] = {{"_p_ModcDetArrayTP", 0, "ModcDetArrayTP *", 0, 0, 0, 0},{"_p_ModcDetArrayTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__DoubleArrayTP[] = {{"_DoubleArrayTP", 0, "double *|DoubleArrayTP", 0, 0, 0, 0},{"_p_MjdTP", 0, 0, 0, 0, 0, 0},{"_DoubleArrayTP", 0, 0, 0, 0, 0, 0},{"_p_double", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_OrbitArrayTP[] = {{"_p_OrbitArrayTP", 0, "OrbitArrayTP *", 0, 0, 0, 0},{"_p_OrbitArrayTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_ModcOrbitArrayTP[] = {{"_p_ModcOrbitArrayTP", 0, "ModcOrbitArrayTP *", 0, 0, 0, 0},{"_p_ModcOrbitArrayTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_double[] = {{"_p_double", 0, "double *", 0, 0, 0, 0},{"_p_MjdTP", 0, 0, 0, 0, 0, 0},{"_DoubleArrayTP", 0, 0, 0, 0, 0, 0},{"_p_double", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_SucceedTP[] = {{"_p_SucceedTP", 0, "SucceedTP *", 0, 0, 0, 0},{"_p_SucceedTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_CovMatrixTP[] = {{"_p_CovMatrixTP", 0, "CovMatrixTP *", 0, 0, 0, 0},{"_p_CovMatrixTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_IdTP[] = {{"_p_IdTP", 0, "long *|IdTP *", 0, 0, 0, 0},{"_p_IdTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_time_t[] = {{"_p_time_t", 0, "time_t *", 0, 0, 0, 0},{"_p_time_t", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_BoolTP[] = {{"_p_BoolTP", 0, "int *|BoolTP *", 0, 0, 0, 0},{"_p_BoolTP", 0, 0, 0, 0, 0, 0},{"_p_FlagTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_FlagTP[] = {{"_p_FlagTP", 0, "int *|FlagTP *", 0, 0, 0, 0},{"_p_FlagTP", 0, 0, 0, 0, 0, 0},{"_p_BoolTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_MjdTP[] = {{"_p_MjdTP", 0, "double *|MjdTP *", 0, 0, 0, 0},{"_p_MjdTP", 0, 0, 0, 0, 0, 0},{"_DoubleArrayTP", 0, 0, 0, 0, 0, 0},{"_p_double", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_ModcDetTP[] = {{"_p_ModcDetTP", 0, "ModcDetTP *", 0, 0, 0, 0},{"_p_ModcDetTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_TaxonomicTP[] = {{"_p_TaxonomicTP", 0, "TaxonomicTP *", 0, 0, 0, 0},{"_p_TaxonomicTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_StringTP, 
_swigt__p_OrbitTP, 
_swigt__p_ModcOrbitTP, 
_swigt__p_ModcDetArrayTP, 
_swigt__DoubleArrayTP, 
_swigt__p_OrbitArrayTP, 
_swigt__p_ModcOrbitArrayTP, 
_swigt__p_double, 
_swigt__p_SucceedTP, 
_swigt__p_CovMatrixTP, 
_swigt__p_IdTP, 
_swigt__p_time_t, 
_swigt__p_BoolTP, 
_swigt__p_FlagTP, 
_swigt__p_MjdTP, 
_swigt__p_ModcDetTP, 
_swigt__p_TaxonomicTP, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_constant_info swig_constants[] = {
{0,0,0,0,0,0}
};
#ifdef __cplusplus
}
#endif
static swig_variable_info swig_variables[] = {
{0,0,0,0}
};
static swig_command_info swig_commands[] = {
{"PS::MOPS::DB::Orbitc::new_doubleArray", _wrap_new_doubleArray},
{"PS::MOPS::DB::Orbitc::delete_doubleArray", _wrap_delete_doubleArray},
{"PS::MOPS::DB::Orbitc::doubleArray_getitem", _wrap_doubleArray_getitem},
{"PS::MOPS::DB::Orbitc::doubleArray_setitem", _wrap_doubleArray_setitem},
{"PS::MOPS::DB::Orbitc::modco_toStruct", _wrap_modco_toStruct},
{"PS::MOPS::DB::Orbitc::modco_toStructArray", _wrap_modco_toStructArray},
{"PS::MOPS::DB::Orbitc::modco_getCount", _wrap_modco_getCount},
{"PS::MOPS::DB::Orbitc::modco_create", _wrap_modco_create},
{"PS::MOPS::DB::Orbitc::modco_retrieve", _wrap_modco_retrieve},
{"PS::MOPS::DB::Orbitc::modco_retrieveByValue", _wrap_modco_retrieveByValue},
{"PS::MOPS::DB::Orbitc::modco_retrieveByDetectionId", _wrap_modco_retrieveByDetectionId},
{"PS::MOPS::DB::Orbitc::modco_insertByValue", _wrap_modco_insertByValue},
{"PS::MOPS::DB::Orbitc::modco_insert", _wrap_modco_insert},
{"PS::MOPS::DB::Orbitc::modco_attributeDetections", _wrap_modco_attributeDetections},
{"PS::MOPS::DB::Orbitc::modco_clearDetections", _wrap_modco_clearDetections},
{"PS::MOPS::DB::Orbitc::modco_update", _wrap_modco_update},
{"PS::MOPS::DB::Orbitc::modco_delete", _wrap_modco_delete},
{"PS::MOPS::DB::Orbitc::modco_free", _wrap_modco_free},
{"PS::MOPS::DB::Orbitc::modco_freeArray", _wrap_modco_freeArray},
{"PS::MOPS::DB::Orbitc::modco_freeStruct", _wrap_modco_freeStruct},
{"PS::MOPS::DB::Orbitc::modco_freeArrayStruct", _wrap_modco_freeArrayStruct},
{"PS::MOPS::DB::Orbitc::modco_getId", _wrap_modco_getId},
{"PS::MOPS::DB::Orbitc::modco_getQ", _wrap_modco_getQ},
{"PS::MOPS::DB::Orbitc::modco_getE", _wrap_modco_getE},
{"PS::MOPS::DB::Orbitc::modco_getI", _wrap_modco_getI},
{"PS::MOPS::DB::Orbitc::modco_getNode", _wrap_modco_getNode},
{"PS::MOPS::DB::Orbitc::modco_getLongPeri", _wrap_modco_getLongPeri},
{"PS::MOPS::DB::Orbitc::modco_getTimePeri", _wrap_modco_getTimePeri},
{"PS::MOPS::DB::Orbitc::modco_getEpoch", _wrap_modco_getEpoch},
{"PS::MOPS::DB::Orbitc::modco_getDetCount", _wrap_modco_getDetCount},
{"PS::MOPS::DB::Orbitc::modco_getChiSquared", _wrap_modco_getChiSquared},
{"PS::MOPS::DB::Orbitc::modco_getOMinusC", _wrap_modco_getOMinusC},
{"PS::MOPS::DB::Orbitc::modco_getIsFake", _wrap_modco_getIsFake},
{"PS::MOPS::DB::Orbitc::modco_getFlags", _wrap_modco_getFlags},
{"PS::MOPS::DB::Orbitc::modco_getUpdated", _wrap_modco_getUpdated},
{"PS::MOPS::DB::Orbitc::modco_getMoid", _wrap_modco_getMoid},
{"PS::MOPS::DB::Orbitc::modco_getMoidLong", _wrap_modco_getMoidLong},
{"PS::MOPS::DB::Orbitc::modco_getObjectName", _wrap_modco_getObjectName},
{"PS::MOPS::DB::Orbitc::modco_getTaxonomicType", _wrap_modco_getTaxonomicType},
{"PS::MOPS::DB::Orbitc::modco_getRotationPeriod", _wrap_modco_getRotationPeriod},
{"PS::MOPS::DB::Orbitc::modco_getAmplitude", _wrap_modco_getAmplitude},
{"PS::MOPS::DB::Orbitc::modco_getRotationEpoch", _wrap_modco_getRotationEpoch},
{"PS::MOPS::DB::Orbitc::modco_getHV", _wrap_modco_getHV},
{"PS::MOPS::DB::Orbitc::modco_getHSS", _wrap_modco_getHSS},
{"PS::MOPS::DB::Orbitc::modco_getG", _wrap_modco_getG},
{"PS::MOPS::DB::Orbitc::modco_getAlbedo", _wrap_modco_getAlbedo},
{"PS::MOPS::DB::Orbitc::modco_getPoleLat", _wrap_modco_getPoleLat},
{"PS::MOPS::DB::Orbitc::modco_getPoleLong", _wrap_modco_getPoleLong},
{"PS::MOPS::DB::Orbitc::modco_getDetections", _wrap_modco_getDetections},
{"PS::MOPS::DB::Orbitc::modco_next", _wrap_modco_next},
{"PS::MOPS::DB::Orbitc::modco_prev", _wrap_modco_prev},
{"PS::MOPS::DB::Orbitc::modco_nextDetection", _wrap_modco_nextDetection},
{"PS::MOPS::DB::Orbitc::modco_prevDetection", _wrap_modco_prevDetection},
{0,0}
};

#ifdef __cplusplus
extern "C"
#endif

XS(SWIG_init) {
    dXSARGS;
    int i;
    static int _init = 0;
    if (!_init) {
        SWIG_Perl_LookupTypePointer();
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }	
        _init = 1;
    }
    
    /* Install commands */
    for (i = 0; swig_commands[i].name; i++) {
        newXS((char*) swig_commands[i].name,swig_commands[i].wrapper, (char*)__FILE__);
    }
    
    /* Install variables */
    for (i = 0; swig_variables[i].name; i++) {
        SV *sv;
        sv = perl_get_sv((char*) swig_variables[i].name, TRUE | 0x2);
        if (swig_variables[i].type) {
            SWIG_MakePtr(sv,(void *)1, *swig_variables[i].type,0);
        } else {
            sv_setiv(sv,(IV) 0);
        }
        swig_create_magic(sv, (char *) swig_variables[i].name, swig_variables[i].set, swig_variables[i].get); 
    }
    
    /* Install constant */
    for (i = 0; swig_constants[i].type; i++) {
        SV *sv;
        sv = perl_get_sv((char*)swig_constants[i].name, TRUE | 0x2);
        switch(swig_constants[i].type) {
            case SWIG_INT:
            sv_setiv(sv, (IV) swig_constants[i].lvalue);
            break;
            case SWIG_FLOAT:
            sv_setnv(sv, (double) swig_constants[i].dvalue);
            break;
            case SWIG_STRING:
            sv_setpv(sv, (char *) swig_constants[i].pvalue);
            break;
            case SWIG_POINTER:
            SWIG_MakePtr(sv, swig_constants[i].pvalue, *(swig_constants[i].ptype),0);
            break;
            case SWIG_BINARY:
            SWIG_MakePackedObj(sv, swig_constants[i].pvalue, swig_constants[i].lvalue, *(swig_constants[i].ptype));
            break;
            default:
            break;
        }
        SvREADONLY_on(sv);
    }
    
    ST(0) = &PL_sv_yes;
    XSRETURN(1);
}

