#!/usr/bin/env python

import sys;
import slalib;
import math;

foo = [float(x) for x in sys.argv[1:]]
a = tuple(foo[0:3])
b = tuple(foo[3:6])

# Separation
res = 180 / math.pi * slalib.sla_dsepv(a, b)

# Cross product
cross = (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])

# Output
print "%.2f" % res;
print cross;
