# $Id:  $

PROG = ingest_monitor.py update_chunk.pl start_mops.pl propagate_ssm.py update_mops_data.py ET_minus_UT
MOPS_BIN = ${MOPS_HOME}/bin

$(PROG):

install:
	/bin/cp $(PROG) $(MOPS_BIN)
