# $Id: Makefile 1508 2007-02-20 18:22:31Z fpierfed $

MOPS_BIN = ${MOPS_HOME}/bin
MOPS_LIB = ${MOPS_HOME}/lib
MOPS_INC = ${MOPS_HOME}/include

INSTALL = /usr/bin/install


all: install

install:
	$(INSTALL) ephem_pipeline.py $(MOPS_BIN)

  
