/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of GCR.xs. Do not edit this file, edit GCR.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "GCR.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include <gcf/gcf.h>

#include "const-c.inc"

#line 21 "GCR.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 163 "GCR.c"

/* INCLUDE:  Including 'const-xs.inc' from 'GCR.xs' */


XS_EUPXS(XS_PS__MOPS__GCR_constant); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PS__MOPS__GCR_constant)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 4 "./const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	IV		iv;
	/* NV		nv;	Uncomment this if you need to return NVs */
	/* const char	*pv;	Uncomment this if you need to return PVs */
#line 188 "GCR.c"
	SV *	sv = ST(0)
;
	const char *	s = SvPV(sv, len);
#line 18 "./const-xs.inc"
        /* Change this to constant(aTHX_ s, len, &iv, &nv);
           if you need to return both NVs and IVs */
	type = constant(aTHX_ s, len, &iv);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv =
	    sv_2mortal(newSVpvf("%s is not a valid PS::MOPS::GCR macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined PS::MOPS::GCR macro %s, used",
				   s));
          PUSHs(sv);
          break;
        case PERL_constant_ISIV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break;
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
	/* Uncomment this if you need to return PVs
        case PERL_constant_ISPV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break; */
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing PS::MOPS::GCR macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 266 "GCR.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'GCR.xs' from 'const-xs.inc' */


XS_EUPXS(XS_PS__MOPS__GCR_compute_gcr); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PS__MOPS__GCR_compute_gcr)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "dets_aref");
    {
	SV *	dets_aref = ST(0)
;
	double	RETVAL;
	dXSTARG;
#line 19 "GCR.xs"
        I32 numdets = 0;
        double gcr_arcsec = 42;
        int i;
        HV *det_hv;
        SV *det_href;
        SV **mjd_svp;
        SV **ra_svp;
        SV **dec_svp;
        double mjd, ra, dec;

        if ((!SvROK(dets_aref))
            || (SvTYPE(SvRV(dets_aref)) != SVt_PVAV)
            || ((numdets = av_len((AV *) SvRV(dets_aref))) < 0)) {
            XSRETURN_UNDEF;
        }
        double t[numdets];
        double c[numdets][2];
        double nt[numdets];
        double rs[numdets][2];

#line 308 "GCR.c"
#line 40 "GCR.xs"
        /* Walk list of detections, stuff params, calc GCR. */
        numdets++;  // is highest index, cvt to num elements
        for (i = 0; i < numdets; i++) {
            det_href = (SV *) (*av_fetch((AV *) SvRV(dets_aref), i, 0));

            /* Check that we got an HV. */
            det_hv = (HV *) SvRV(det_href);

            /* Got an HV for the det, now look up key-vals. */
            mjd_svp = hv_fetch(det_hv, "epoch", sizeof("epoch") - 1, 0);
            ra_svp = hv_fetch(det_hv, "ra", sizeof("ra") - 1, 0);
            dec_svp = hv_fetch(det_hv, "dec", sizeof("dec") - 1, 0);
            if (mjd_svp == NULL || ra_svp == NULL || dec_svp == NULL)
                XSRETURN_UNDEF;

            /* Look up our values. */
            mjd = SvNV(*mjd_svp);
            ra = SvNV(*ra_svp);
            dec = SvNV(*dec_svp);

            t[i] = mjd;
            c[i][0] = ra * M_PI / 180;
            c[i][1] = dec * M_PI / 180;
        }

        gcfparam gcf;
        gcf.nObs = numdets;
        gcf.ntime = nt;
        gcf.rs = rs;
        gcFit(&gcf, t, c);
        RETVAL = gcRms(&gcf);
#line 341 "GCR.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_PS__MOPS__GCR_compute_vel); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PS__MOPS__GCR_compute_vel)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "dets_aref");
    {
	SV *	dets_aref = ST(0)
;
	double	RETVAL;
	dXSTARG;
#line 78 "GCR.xs"
        I32 numdets = 0;
        double gcr_vel = 42;
        int i;
        HV *det_hv;
        SV *det_href;
        SV **mjd_svp;
        SV **ra_svp;
        SV **dec_svp;
        double mjd, ra, dec;

        if ((!SvROK(dets_aref))
            || (SvTYPE(SvRV(dets_aref)) != SVt_PVAV)
            || ((numdets = av_len((AV *) SvRV(dets_aref))) < 0)) {
            XSRETURN_UNDEF;
        }
        double t[numdets];
        double c[numdets][2];
        double nt[numdets];
        double rs[numdets][2];

#line 380 "GCR.c"
#line 99 "GCR.xs"
        /* Walk list of detections, stuff params, calc GCR. */
        numdets++;  // is highest index, cvt to num elements
        for (i = 0; i < numdets; i++) {
            det_href = (SV *) (*av_fetch((AV *) SvRV(dets_aref), i, 0));

            /* Check that we got an HV. */
            det_hv = (HV *) SvRV(det_href);

            /* Got an HV for the det, now look up key-vals. */
            mjd_svp = hv_fetch(det_hv, "epoch", sizeof("epoch") - 1, 0);
            ra_svp = hv_fetch(det_hv, "ra", sizeof("ra") - 1, 0);
            dec_svp = hv_fetch(det_hv, "dec", sizeof("dec") - 1, 0);
            if (mjd_svp == NULL || ra_svp == NULL || dec_svp == NULL)
                XSRETURN_UNDEF;

            /* Look up our values. */
            mjd = SvNV(*mjd_svp);
            ra = SvNV(*ra_svp);
            dec = SvNV(*dec_svp);

            t[i] = mjd;
            c[i][0] = ra * M_PI / 180;
            c[i][1] = dec * M_PI / 180;
        }

        gcfparam gcf;
        gcf.nObs = numdets;
        gcf.ntime = nt;
        gcf.rs = rs;
        gcFit(&gcf, t, c);
        RETVAL = gcVel(&gcf);
#line 413 "GCR.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_PS__MOPS__GCR); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_PS__MOPS__GCR)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("PS::MOPS::GCR::constant", XS_PS__MOPS__GCR_constant, file);
        newXS("PS::MOPS::GCR::compute_gcr", XS_PS__MOPS__GCR_compute_gcr, file);
        newXS("PS::MOPS::GCR::compute_vel", XS_PS__MOPS__GCR_compute_vel, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

