/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.23
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */


#ifndef SWIG_TEMPLATE_DISAMBIGUATOR
#  if defined(__SUNPRO_CC) 
#    define SWIG_TEMPLATE_DISAMBIGUATOR template
#  else
#    define SWIG_TEMPLATE_DISAMBIGUATOR 
#  endif
#endif

/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#  if !defined(STATIC_LINKED)
#    define SWIGEXPORT(a) __declspec(dllexport) a
#  else
#    define SWIGEXPORT(a) a
#  endif
#else
#  define SWIGEXPORT(a) a
#endif

#define SWIGRUNTIME(x) static x

#ifndef SWIGINLINE
#if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#  define SWIGINLINE inline
#else
#  define SWIGINLINE
#endif
#endif


/* This should only be incremented when either the layout of swig_type_info changes,
   or for whatever reason, the runtime changes incompatibly */
#define SWIG_RUNTIME_VERSION "1"

/* define SWIG_TYPE_TABLE_NAME as "SWIG_TYPE_TABLE" */
#ifdef SWIG_TYPE_TABLE
#define SWIG_QUOTE_STRING(x) #x
#define SWIG_EXPAND_AND_QUOTE_STRING(x) SWIG_QUOTE_STRING(x)
#define SWIG_TYPE_TABLE_NAME SWIG_EXPAND_AND_QUOTE_STRING(SWIG_TYPE_TABLE)
#else
#define SWIG_TYPE_TABLE_NAME
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

static swig_type_info *swig_type_list = 0;
static swig_type_info **swig_type_list_handle = &swig_type_list;

/* 
   Compare two type names skipping the space characters, therefore
   "char*" == "char *" and "Class<int>" == "Class<int >", etc.

   Return 0 when the two name types are equivalent, as in
   strncmp, but skipping ' '.
*/
static int
SWIG_TypeNameComp(const char *f1, const char *l1,
		  const char *f2, const char *l2) {
  for (;(f1 != l1) && (f2 != l2); ++f1, ++f2) {
    while ((*f1 == ' ') && (f1 != l1)) ++f1;
    while ((*f2 == ' ') && (f2 != l2)) ++f2;
    if (*f1 != *f2) return *f1 - *f2;
  }
  return (l1 - f1) - (l2 - f2);
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
*/
static int
SWIG_TypeEquiv(const char *nb, const char *tb) {
  int equiv = 0;
  const char* te = tb + strlen(tb);
  const char* ne = nb;
  while (!equiv && *ne) {
    for (nb = ne; *ne; ++ne) {
      if (*ne == '|') break;
    }
    equiv = SWIG_TypeNameComp(nb, ne, tb, te) == 0;
    if (*ne) ++ne;
  }
  return equiv;
}
  

/* Register a type mapping with the type-checking */
static swig_type_info *
SWIG_TypeRegister(swig_type_info *ti) {
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = *swig_type_list_handle;
  while (tc) {
    /* check simple type equivalence */
    int typeequiv = (strcmp(tc->name, ti->name) == 0);   
    /* check full type equivalence, resolving typedefs */
    if (!typeequiv) {
      /* only if tc is not a typedef (no '|' on it) */
      if (tc->str && ti->str && !strstr(tc->str,"|")) {
	typeequiv = SWIG_TypeEquiv(ti->str,tc->str);
      }
    }
    if (typeequiv) {
      /* Already exists in the table.  Just add additional types to the list */
      if (ti->clientdata) tc->clientdata = ti->clientdata;
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = *swig_type_list_handle;
  *swig_type_list_handle = ti;

  /* Build linked lists */
  l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;
  head->next = next;

  return ret;
}

/* Check the typename */
static swig_type_info *
SWIG_TypeCheck(char *c, swig_type_info *ty) {
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
        s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Cast a pointer up an inheritance hierarchy */
static SWIGINLINE void *
SWIG_TypeCast(swig_type_info *ty, void *ptr) {
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Dynamic pointer casting. Down an inheritance hierarchy */
static swig_type_info *
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/* Return the name associated with this type */
static SWIGINLINE const char *
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/* Return the pretty name associated with this type,
   that is an unmangled type name in a form presentable to the user.
*/
static const char *
SWIG_TypePrettyName(const swig_type_info *type) {
  /* The "str" field contains the equivalent pretty names of the
     type, separated by vertical-bar characters.  We choose
     to print the last name, as it is often (?) the most
     specific. */
  if (type->str != NULL) {
    const char *last_name = type->str;
    const char *s;
    for (s = type->str; *s; s++)
      if (*s == '|') last_name = s+1;
    return last_name;
  }
  else
    return type->name;
}

/* Search for a swig_type_info structure */
static swig_type_info *
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = *swig_type_list_handle;
  while (ty) {
    if (ty->str && (SWIG_TypeEquiv(ty->str,name))) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
static void
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata) return;
  /* if (ti->clientdata == clientdata) return; */
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = *swig_type_list_handle;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0))
          SWIG_TypeClientData(tc,clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* Pack binary data into a string */
static char *
SWIG_PackData(char *c, void *ptr, size_t sz) {
  static char hex[17] = "0123456789abcdef";
  unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu =  u + sz;
  register unsigned char uu;
  for (; u != eu; ++u) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
static char *
SWIG_UnpackData(char *c, void *ptr, size_t sz) {
  register unsigned char uu = 0;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu =  u + sz;
  for (; u != eu; ++u) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

/* This function will propagate the clientdata field of type to
* any new swig_type_info structures that have been added into the list
* of equivalent types.  It is like calling
* SWIG_TypeClientData(type, clientdata) a second time.
*/
static void
SWIG_PropagateClientData(swig_type_info *type) {
  swig_type_info *equiv = type->next;
  swig_type_info *tc;
  if (!type->clientdata) return;
  while (equiv) {
    if (!equiv->converter) {
      tc = *swig_type_list_handle;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0) && !tc->clientdata)
          SWIG_TypeClientData(tc, type->clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

#ifdef __cplusplus
}
#endif

/* ---------------------------------------------------------------------- -*- c -*-
 * perl5.swg
 *
 * Perl5 runtime library
 * $Header$
 * ----------------------------------------------------------------------------- */

#define SWIGPERL
#define SWIGPERL5
#ifdef __cplusplus
/* Needed on some windows machines---since MS plays funny games with the header files under C++ */
#include <math.h>
#include <stdlib.h>
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

/* Get rid of free and malloc defined by perl */
#undef free
#undef malloc

#ifndef pTHX_
#define pTHX_
#endif

#include <string.h>
#ifdef __cplusplus
}
#endif

/* Macro to call an XS function */

#ifdef PERL_OBJECT 
#  define SWIG_CALLXS(_name) _name(cv,pPerl) 
#else 
#  ifndef MULTIPLICITY 
#    define SWIG_CALLXS(_name) _name(cv) 
#  else 
#    define SWIG_CALLXS(_name) _name(PERL_GET_THX, cv) 
#  endif 
#endif 

/* Contract support */

#define SWIG_contract_assert(expr,msg) if (!(expr)) { SWIG_croak(msg); } else

/* Note: SwigMagicFuncHack is a typedef used to get the C++ compiler to just shut up already */

#ifdef PERL_OBJECT
#define MAGIC_PPERL  CPerlObj *pPerl = (CPerlObj *) this;
typedef int (CPerlObj::*SwigMagicFunc)(SV *, MAGIC *);

#ifdef __cplusplus
extern "C" {
#endif
typedef int (CPerlObj::*SwigMagicFuncHack)(SV *, MAGIC *);
#ifdef __cplusplus
}
#endif

#define SWIG_MAGIC(a,b) (SV *a, MAGIC *b)
#define SWIGCLASS_STATIC
#else
#define MAGIC_PPERL
#define SWIGCLASS_STATIC static
#ifndef MULTIPLICITY
#define SWIG_MAGIC(a,b) (SV *a, MAGIC *b)
typedef int (*SwigMagicFunc)(SV *, MAGIC *);

#ifdef __cplusplus
extern "C" {
#endif
typedef int (*SwigMagicFuncHack)(SV *, MAGIC *);
#ifdef __cplusplus
}
#endif


#else
#define SWIG_MAGIC(a,b) (struct interpreter *interp, SV *a, MAGIC *b)
typedef int (*SwigMagicFunc)(struct interpreter *, SV *, MAGIC *);
#ifdef __cplusplus
extern "C" {
#endif
typedef int (*SwigMagicFuncHack)(struct interpreter *, SV *, MAGIC *);
#ifdef __cplusplus
}
#endif

#endif
#endif

#if defined(WIN32) && defined(PERL_OBJECT) && !defined(PerlIO_exportFILE)
#define PerlIO_exportFILE(fh,fl) (FILE*)(fh)
#endif

/* Modifications for newer Perl 5.005 releases */

#if !defined(PERL_REVISION) || ((PERL_REVISION >= 5) && ((PERL_VERSION < 5) || ((PERL_VERSION == 5) && (PERL_SUBVERSION < 50))))
#  ifndef PL_sv_yes
#    define PL_sv_yes sv_yes
#  endif
#  ifndef PL_sv_undef
#    define PL_sv_undef sv_undef
#  endif
#  ifndef PL_na
#    define PL_na na
#  endif
#endif

#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_OWNER 1
#define SWIG_SHADOW 2

/* Common SWIG API */

#ifdef PERL_OBJECT
#  define SWIG_ConvertPtr(obj, pp, type, flags) \
     SWIG_Perl_ConvertPtr(pPerl, obj, pp, type, flags)
#  define SWIG_NewPointerObj(p, type, flags) \
     SWIG_Perl_NewPointerObj(pPerl, p, type, flags)
#  define SWIG_MakePackedObj(sv, p, s, type)	\
     SWIG_Perl_MakePackedObj(pPerl, sv, p, s, type)
#  define SWIG_ConvertPacked(obj, p, s, type, flags) \
     SWIG_Perl_ConvertPacked(pPerl, obj, p, s, type, flags)

#else
#  define SWIG_ConvertPtr(obj, pp, type, flags) \
     SWIG_Perl_ConvertPtr(obj, pp, type, flags)
#  define SWIG_NewPointerObj(p, type, flags) \
     SWIG_Perl_NewPointerObj(p, type, flags)
#  define SWIG_MakePackedObj(sv, p, s, type)	\
     SWIG_Perl_MakePackedObj(sv, p, s, type )
#  define SWIG_ConvertPacked(obj, p, s, type, flags) \
     SWIG_Perl_ConvertPacked(obj, p, s, type, flags)
#endif

/* Perl-specific API */
#ifdef PERL_OBJECT
#  define SWIG_MakePtr(sv, ptr, type, flags) \
     SWIG_Perl_MakePtr(pPerl, sv, ptr, type, flags)
#  define SWIG_SetError(str) \
     SWIG_Perl_SetError(pPerl, str)
#else
#  define SWIG_MakePtr(sv, ptr, type, flags) \
     SWIG_Perl_MakePtr(sv, ptr, type, flags)
#  define SWIG_SetError(str) \
     SWIG_Perl_SetError(str)
#  define SWIG_SetErrorSV(str) \
     SWIG_Perl_SetErrorSV(str)
#endif

#define SWIG_SetErrorf SWIG_Perl_SetErrorf


#ifdef PERL_OBJECT
#  define SWIG_MAYBE_PERL_OBJECT CPerlObj *pPerl,
#else
#  define SWIG_MAYBE_PERL_OBJECT
#endif

/* load the swig_runtime_list_handle variable from the interpreter */
static void SWIG_Perl_LookupTypePointer() {
  SV *pointer;

  /* first check if pointer already created */
  pointer = get_sv("swig_runtime_data::type_pointer" SWIG_RUNTIME_VERSION SWIG_TYPE_TABLE_NAME, FALSE);
  if (pointer && SvOK(pointer)) {
    swig_type_list_handle = INT2PTR(swig_type_info **, SvIV(pointer));
  } else {
    /* create a new pointer */
    pointer = get_sv("swig_runtime_data::type_pointer" SWIG_RUNTIME_VERSION SWIG_TYPE_TABLE_NAME, TRUE);
    sv_setiv(pointer, PTR2IV(swig_type_list_handle));
  }
}

static swig_type_info *
SWIG_Perl_TypeCheckRV(SWIG_MAYBE_PERL_OBJECT SV *rv, swig_type_info *ty) {
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (sv_derived_from(rv, (char *) s->name)) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
        s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Function for getting a pointer value */

static int
SWIG_Perl_ConvertPtr(SWIG_MAYBE_PERL_OBJECT SV *sv, void **ptr, swig_type_info *_t, int flags) {
  swig_type_info *tc;
  void *voidptr = (void *)0;

  /* If magical, apply more magic */
  if (SvGMAGICAL(sv))
    mg_get(sv);

  /* Check to see if this is an object */
  if (sv_isobject(sv)) {
    SV *tsv = (SV*) SvRV(sv);
    IV tmp = 0;
    if ((SvTYPE(tsv) == SVt_PVHV)) {
      MAGIC *mg;
      if (SvMAGICAL(tsv)) {
        mg = mg_find(tsv,'P');
        if (mg) {
          sv = mg->mg_obj;
          if (sv_isobject(sv)) {
            tmp = SvIV((SV*)SvRV(sv));
          }
        }
      } else {
        return -1;
      }
    } else {
      tmp = SvIV((SV*)SvRV(sv));
    }
    voidptr = (void *)tmp;
    if (!_t) {
      *(ptr) = voidptr;
      return 0;
    }
  } else if (! SvOK(sv)) {            /* Check for undef */
    *(ptr) = (void *) 0;
    return 0;
  } else if (SvTYPE(sv) == SVt_RV) {  /* Check for NULL pointer */
    *(ptr) = (void *) 0;
    if (!SvROK(sv))
      return 0;
    else
      return -1;
  } else {                            /* Don't know what it is */
    *(ptr) = (void *) 0;
    return -1;
  }
  if (_t) {
    /* Now see if the types match */
    char *_c = HvNAME(SvSTASH(SvRV(sv)));
    tc = SWIG_TypeCheck(_c,_t);
    if (!tc) {
      *ptr = voidptr;
      return -1;
    }
    *ptr = SWIG_TypeCast(tc,voidptr);
    return 0;
  }
  *ptr = voidptr;
  return 0;
}

static void
SWIG_Perl_MakePtr(SWIG_MAYBE_PERL_OBJECT SV *sv, void *ptr, swig_type_info *t, int flags) {
  if (ptr && (flags & SWIG_SHADOW)) {
    SV *self;
    SV *obj=newSV(0);
    HV *hash=newHV();
    HV *stash;
    sv_setref_pv(obj, (char *) t->name, ptr);
    stash=SvSTASH(SvRV(obj));
    if (flags & SWIG_OWNER) {
      HV *hv;
      GV *gv=*(GV**)hv_fetch(stash, "OWNER", 5, TRUE);
      if (!isGV(gv))
        gv_init(gv, stash, "OWNER", 5, FALSE);
      hv=GvHVn(gv);
      hv_store_ent(hv, obj, newSViv(1), 0);
    }
    sv_magic((SV *)hash, (SV *)obj, 'P', Nullch, 0);
    SvREFCNT_dec(obj);
    self=newRV_noinc((SV *)hash);
    sv_setsv(sv, self);
    SvREFCNT_dec((SV *)self);
    sv_bless(sv, stash);
  }
  else {
    sv_setref_pv(sv, (char *) t->name, ptr);
  }
}

static SWIGINLINE SV *
SWIG_Perl_NewPointerObj(SWIG_MAYBE_PERL_OBJECT void *ptr, swig_type_info *t, int flags) {
  SV *result = sv_newmortal();
  SWIG_MakePtr(result, ptr, t, flags);
  return result;
}

static void
  SWIG_Perl_MakePackedObj(SWIG_MAYBE_PERL_OBJECT SV *sv, void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  sv_setpv(sv, result);
}

/* Convert a packed value value */
static int
SWIG_Perl_ConvertPacked(SWIG_MAYBE_PERL_OBJECT SV *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c = 0;

  if ((!obj) || (!SvOK(obj))) return -1;
  c = SvPV(obj, PL_na);
  /* Pointer values must start with leading underscore */
  if (*c != '_') return -1;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) return -1;
  }
  return 0;
}

static SWIGINLINE void
SWIG_Perl_SetError(SWIG_MAYBE_PERL_OBJECT const char *error) {
  if (error) sv_setpv(perl_get_sv("@", TRUE), error);
}

static SWIGINLINE void
SWIG_Perl_SetErrorSV(SWIG_MAYBE_PERL_OBJECT SV *error) {
  if (error) sv_setsv(perl_get_sv("@", TRUE), error);
}

static void
SWIG_Perl_SetErrorf(const char *fmt, ...) {
  va_list args;
  va_start(args, fmt);
  sv_vsetpvfn(perl_get_sv("@", TRUE), fmt, strlen(fmt), &args, Null(SV**), 0, Null(bool*));
  va_end(args);
}

/* Macros for low-level exception handling */
#define SWIG_fail       goto fail
#define SWIG_croak(x)   { SWIG_SetError(x); goto fail; }
#define SWIG_croakSV(x) { SWIG_SetErrorSV(x); goto fail; }
/* most preprocessors do not support vararg macros :-( */
/* #define SWIG_croakf(x...) { SWIG_SetErrorf(x); goto fail; } */


typedef XS(SwigPerlWrapper);
typedef SwigPerlWrapper *SwigPerlWrapperPtr;

/* Structure for command table */
typedef struct {
  const char         *name;
  SwigPerlWrapperPtr  wrapper;
} swig_command_info;

/* Information for constant table */

#define SWIG_INT     1
#define SWIG_FLOAT   2
#define SWIG_STRING  3
#define SWIG_POINTER 4
#define SWIG_BINARY  5

/* Constant information structure */
typedef struct swig_constant_info {
    int              type;
    const char      *name;
    long             lvalue;
    double           dvalue;
    void            *pvalue;
    swig_type_info **ptype;
} swig_constant_info;

#ifdef __cplusplus
}
#endif

/* Structure for variable table */
typedef struct {
  const char   *name;
  SwigMagicFunc   set;
  SwigMagicFunc   get;
  swig_type_info  **type;
} swig_variable_info;

/* Magic variable code */
#ifndef PERL_OBJECT
#define swig_create_magic(s,a,b,c) _swig_create_magic(s,a,b,c)
  #ifndef MULTIPLICITY
     static void _swig_create_magic(SV *sv, char *name, int (*set)(SV *, MAGIC *), int (*get)(SV *,MAGIC *)) {
  #else
     static void _swig_create_magic(SV *sv, char *name, int (*set)(struct interpreter*, SV *, MAGIC *), int (*get)(struct interpreter*, SV *,MAGIC *)) {
  #endif
#else
#  define swig_create_magic(s,a,b,c) _swig_create_magic(pPerl,s,a,b,c)
static void _swig_create_magic(CPerlObj *pPerl, SV *sv, const char *name, int (CPerlObj::*set)(SV *, MAGIC *), int (CPerlObj::*get)(SV *, MAGIC *)) {
#endif
  MAGIC *mg;
  sv_magic(sv,sv,'U',(char *) name,strlen(name));
  mg = mg_find(sv,'U');
  mg->mg_virtual = (MGVTBL *) malloc(sizeof(MGVTBL));
  mg->mg_virtual->svt_get = (SwigMagicFuncHack) get;
  mg->mg_virtual->svt_set = (SwigMagicFuncHack) set;
  mg->mg_virtual->svt_len = 0;
  mg->mg_virtual->svt_clear = 0;
  mg->mg_virtual->svt_free = 0;
}






#ifdef do_open
  #undef do_open
#endif
#ifdef do_close
  #undef do_close
#endif
#ifdef scalar
  #undef scalar
#endif
#ifdef list
  #undef list
#endif
#ifdef apply
  #undef apply
#endif
#ifdef convert
  #undef convert
#endif
#ifdef Error
  #undef Error
#endif
#ifdef form
  #undef form
#endif
#ifdef vform
  #undef vform
#endif
#ifdef LABEL
  #undef LABEL
#endif
#ifdef METHOD
  #undef METHOD
#endif
#ifdef Move
  #undef Move
#endif
#ifdef yylex
  #undef yylex
#endif
#ifdef yyparse
  #undef yyparse
#endif
#ifdef yyerror
  #undef yyerror
#endif
#ifdef invert
  #undef invert
#endif
#ifdef ref
  #undef ref
#endif
#ifdef ENTER
  #undef ENTER
#endif


/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_MjdTP swig_types[0] 
#define  SWIGTYPE_p_SucceedTP swig_types[1] 
#define  SWIGTYPE_p_ObservationArrayTP swig_types[2] 
#define  SWIGTYPE_p_ModcDetArrayTP swig_types[3] 
#define  SWIGTYPE_DoubleArrayTP swig_types[4] 
#define  SWIGTYPE_p_ModcObsArrayTP swig_types[5] 
#define  SWIGTYPE_p_IdTP swig_types[6] 
#define  SWIGTYPE_p_BoolTP swig_types[7] 
#define  SWIGTYPE_p_double swig_types[8] 
#define  SWIGTYPE_p_ModcObsTP swig_types[9] 
#define  SWIGTYPE_p_ObservationTP swig_types[10] 
#define  SWIGTYPE_p_ModcDetTP swig_types[11] 
static swig_type_info *swig_types[13];

/* -------- TYPES TABLE (END) -------- */

#define SWIG_init    boot_PS__MOPS__DB__Observation

#define SWIG_name   "PS::MOPS::DB::Observationc::boot_PS__MOPS__DB__Observation"
#define SWIG_prefix "PS::MOPS::DB::Observationc::"

#ifdef __cplusplus
extern "C"
#endif
#ifndef PERL_OBJECT
#ifndef MULTIPLICITY
SWIGEXPORT(void) SWIG_init (CV* cv);
#else
SWIGEXPORT(void) SWIG_init (pTHXo_ CV* cv);
#endif
#else
SWIGEXPORT(void) SWIG_init (CV *cv, CPerlObj *);
#endif


static double *new_doubleArray(int nelements) { 
  return (double *) calloc(nelements,sizeof(double)); 
}

static void delete_doubleArray(double *ary) { 
  free(ary); 
}

static double doubleArray_getitem(double *ary, int index) {
    return ary[index];
}
static void doubleArray_setitem(double *ary, int index, double value) {
    ary[index] = value;
}


#include "modc.h"

#ifdef PERL_OBJECT
#define MAGIC_CLASS _wrap_PS::MOPS::DB::Observation_var::
class _wrap_PS::MOPS::DB::Observation_var : public CPerlObj {
public:
#else
#define MAGIC_CLASS
#endif
SWIGCLASS_STATIC int swig_magic_readonly(pTHX_ SV *sv, MAGIC *mg) {
    MAGIC_PPERL
    sv = sv; mg = mg;
    croak("Value is read-only.");
    return 0;
}


#ifdef PERL_OBJECT
};
#endif

#ifdef __cplusplus
extern "C" {
#endif
XS(_wrap_new_doubleArray) {
    {
        int arg1 ;
        double *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: new_doubleArray(nelements);");
        }
        arg1 = (int) SvIV(ST(0));
        result = (double *)new_doubleArray(arg1);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_double, 0|0);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_delete_doubleArray) {
    {
        double *arg1 = (double *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: delete_doubleArray(ary);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_double,0) < 0) {
                SWIG_croak("Type error in argument 1 of delete_doubleArray. Expected _p_double");
            }
        }
        delete_doubleArray(arg1);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_doubleArray_getitem) {
    {
        double *arg1 = (double *) 0 ;
        int arg2 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: doubleArray_getitem(ary,index);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_double,0) < 0) {
                SWIG_croak("Type error in argument 1 of doubleArray_getitem. Expected _p_double");
            }
        }
        arg2 = (int) SvIV(ST(1));
        result = (double)doubleArray_getitem(arg1,arg2);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_doubleArray_setitem) {
    {
        double *arg1 = (double *) 0 ;
        int arg2 ;
        double arg3 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 3) || (items > 3)) {
            SWIG_croak("Usage: doubleArray_setitem(ary,index,value);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_double,0) < 0) {
                SWIG_croak("Type error in argument 1 of doubleArray_setitem. Expected _p_double");
            }
        }
        arg2 = (int) SvIV(ST(1));
        arg3 = (double) SvNV(ST(2));
        
        doubleArray_setitem(arg1,arg2,arg3);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_toStruct) {
    {
        ModcObsTP arg1 ;
        ObservationTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_toStruct(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_toStruct. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = modcm_toStruct(arg1);
        
        {
            ObservationTP * resultobj = (ObservationTP *) malloc(sizeof(ObservationTP));
            memmove(resultobj, &result, sizeof(ObservationTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ObservationTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_toStructArray) {
    {
        ModcObsTP arg1 ;
        ObservationArrayTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_toStructArray(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_toStructArray. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = modcm_toStructArray(arg1);
        
        {
            ObservationArrayTP * resultobj = (ObservationArrayTP *) malloc(sizeof(ObservationArrayTP));
            memmove(resultobj, &result, sizeof(ObservationArrayTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ObservationArrayTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_getCount) {
    {
        ModcObsTP arg1 ;
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_getCount(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_getCount. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = (int)modcm_getCount(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_getDetectionCount) {
    {
        ModcObsTP arg1 ;
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_getDetectionCount(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_getDetectionCount. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = (int)modcm_getDetectionCount(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_getDetections) {
    {
        ModcObsTP arg1 ;
        ModcDetArrayTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_getDetections(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_getDetections. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = modcm_getDetections(arg1);
        
        {
            ModcDetArrayTP * resultobj = (ModcDetArrayTP *) malloc(sizeof(ModcDetArrayTP));
            memmove(resultobj, &result, sizeof(ModcDetArrayTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcDetArrayTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_create) {
    {
        MjdTP arg1 ;
        double arg2 ;
        double arg3 ;
        SurveyTP arg4 = (SurveyTP) 0 ;
        MjdTP arg5 ;
        MjdTP arg6 ;
        FilterTP arg7 = (FilterTP) 0 ;
        double arg8 ;
        double arg9 ;
        double arg10 ;
        ObservatoryTP arg11 = (ObservatoryTP) 0 ;
        DoubleArrayTP arg12 = (DoubleArrayTP) 0 ;
        ModcObsTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 12) || (items > 12)) {
            SWIG_croak("Usage: modcm_create(epoch,ra,dec,surveyMode,timeStart,timeStop,filter,limitingMag,raSigma,decSigma,observatory,de);");
        }
        arg1 = (MjdTP) SvNV(ST(0));
        
        arg2 = (double) SvNV(ST(1));
        
        arg3 = (double) SvNV(ST(2));
        
        if (!SvOK((SV*) ST(3))) arg4 = 0;
        else arg4 = (SurveyTP) SvPV(ST(3), PL_na);
        arg5 = (MjdTP) SvNV(ST(4));
        
        arg6 = (MjdTP) SvNV(ST(5));
        
        if (!SvOK((SV*) ST(6))) arg7 = 0;
        else arg7 = (FilterTP) SvPV(ST(6), PL_na);
        arg8 = (double) SvNV(ST(7));
        
        arg9 = (double) SvNV(ST(8));
        
        arg10 = (double) SvNV(ST(9));
        
        if (!SvOK((SV*) ST(10))) arg11 = 0;
        else arg11 = (ObservatoryTP) SvPV(ST(10), PL_na);
        {
            if (SWIG_ConvertPtr(ST(11), (void **) &arg12, SWIGTYPE_DoubleArrayTP,0) < 0) {
                SWIG_croak("Type error in argument 12 of modcm_create. Expected _DoubleArrayTP");
            }
        }
        result = modcm_create(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12);
        
        {
            ModcObsTP * resultobj = (ModcObsTP *) malloc(sizeof(ModcObsTP));
            memmove(resultobj, &result, sizeof(ModcObsTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcObsTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_retrieve) {
    {
        IdTP arg1 ;
        ModcObsTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_retrieve(id);");
        }
        arg1 = (IdTP) SvIV(ST(0));
        result = modcm_retrieve(arg1);
        
        {
            ModcObsTP * resultobj = (ModcObsTP *) malloc(sizeof(ModcObsTP));
            memmove(resultobj, &result, sizeof(ModcObsTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcObsTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_retrieveByValue) {
    {
        MjdTP arg1 ;
        double arg2 ;
        double arg3 ;
        double arg4 ;
        double arg5 ;
        double arg6 ;
        ModcObsTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 6) || (items > 6)) {
            SWIG_croak("Usage: modcm_retrieveByValue(epoch,ra,dec,deltaEpoch,deltaRa,deltaDec);");
        }
        arg1 = (MjdTP) SvNV(ST(0));
        
        arg2 = (double) SvNV(ST(1));
        
        arg3 = (double) SvNV(ST(2));
        
        arg4 = (double) SvNV(ST(3));
        
        arg5 = (double) SvNV(ST(4));
        
        arg6 = (double) SvNV(ST(5));
        
        result = modcm_retrieveByValue(arg1,arg2,arg3,arg4,arg5,arg6);
        
        {
            ModcObsTP * resultobj = (ModcObsTP *) malloc(sizeof(ModcObsTP));
            memmove(resultobj, &result, sizeof(ModcObsTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcObsTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_insert) {
    {
        ModcObsTP arg1 ;
        SucceedTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_insert(obs);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_insert. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = modcm_insert(arg1);
        
        {
            SucceedTP * resultobj = (SucceedTP *) malloc(sizeof(SucceedTP));
            memmove(resultobj, &result, sizeof(SucceedTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_SucceedTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_insertByValue) {
    {
        MjdTP arg1 ;
        double arg2 ;
        double arg3 ;
        SurveyTP arg4 = (SurveyTP) 0 ;
        MjdTP arg5 ;
        MjdTP arg6 ;
        FilterTP arg7 = (FilterTP) 0 ;
        double arg8 ;
        double arg9 ;
        double arg10 ;
        ObservatoryTP arg11 = (ObservatoryTP) 0 ;
        DoubleArrayTP arg12 = (DoubleArrayTP) 0 ;
        ModcObsTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 12) || (items > 12)) {
            SWIG_croak("Usage: modcm_insertByValue(epoch,ra,dec,surveyMode,timeStart,timeStop,filter,limitingMag,raSigma,decSigma,observatory,de);");
        }
        arg1 = (MjdTP) SvNV(ST(0));
        
        arg2 = (double) SvNV(ST(1));
        
        arg3 = (double) SvNV(ST(2));
        
        if (!SvOK((SV*) ST(3))) arg4 = 0;
        else arg4 = (SurveyTP) SvPV(ST(3), PL_na);
        arg5 = (MjdTP) SvNV(ST(4));
        
        arg6 = (MjdTP) SvNV(ST(5));
        
        if (!SvOK((SV*) ST(6))) arg7 = 0;
        else arg7 = (FilterTP) SvPV(ST(6), PL_na);
        arg8 = (double) SvNV(ST(7));
        
        arg9 = (double) SvNV(ST(8));
        
        arg10 = (double) SvNV(ST(9));
        
        if (!SvOK((SV*) ST(10))) arg11 = 0;
        else arg11 = (ObservatoryTP) SvPV(ST(10), PL_na);
        {
            if (SWIG_ConvertPtr(ST(11), (void **) &arg12, SWIGTYPE_DoubleArrayTP,0) < 0) {
                SWIG_croak("Type error in argument 12 of modcm_insertByValue. Expected _DoubleArrayTP");
            }
        }
        result = modcm_insertByValue(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12);
        
        {
            ModcObsTP * resultobj = (ModcObsTP *) malloc(sizeof(ModcObsTP));
            memmove(resultobj, &result, sizeof(ModcObsTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcObsTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_addDetections) {
    {
        ModcObsTP arg1 ;
        ModcDetArrayTP arg2 ;
        SucceedTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: modcm_addDetections(obs,dets);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_addDetections. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        {
            ModcDetArrayTP * argp;
            if (SWIG_ConvertPtr(ST(1),(void **) &argp, SWIGTYPE_p_ModcDetArrayTP,0) < 0) {
                SWIG_croak("Type error in argument 2 of modcm_addDetections. Expected _p_ModcDetArrayTP");
            }
            arg2 = *argp;
        }
        result = modcm_addDetections(arg1,arg2);
        
        {
            SucceedTP * resultobj = (SucceedTP *) malloc(sizeof(SucceedTP));
            memmove(resultobj, &result, sizeof(SucceedTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_SucceedTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_delete) {
    {
        IdTP arg1 ;
        SucceedTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_delete(obsId);");
        }
        arg1 = (IdTP) SvIV(ST(0));
        result = modcm_delete(arg1);
        
        {
            SucceedTP * resultobj = (SucceedTP *) malloc(sizeof(SucceedTP));
            memmove(resultobj, &result, sizeof(SucceedTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_SucceedTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_free) {
    {
        ModcObsTP arg1 ;
        SucceedTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_free(obs);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_free. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = modcm_free(arg1);
        
        {
            SucceedTP * resultobj = (SucceedTP *) malloc(sizeof(SucceedTP));
            memmove(resultobj, &result, sizeof(SucceedTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_SucceedTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_freeArray) {
    {
        ModcObsArrayTP arg1 ;
        SucceedTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_freeArray(obs);");
        }
        {
            ModcObsArrayTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsArrayTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_freeArray. Expected _p_ModcObsArrayTP");
            }
            arg1 = *argp;
        }
        result = modcm_freeArray(arg1);
        
        {
            SucceedTP * resultobj = (SucceedTP *) malloc(sizeof(SucceedTP));
            memmove(resultobj, &result, sizeof(SucceedTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_SucceedTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_freeStruct) {
    {
        ObservationTP arg1 ;
        SucceedTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_freeStruct(obs);");
        }
        {
            ObservationTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ObservationTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_freeStruct. Expected _p_ObservationTP");
            }
            arg1 = *argp;
        }
        result = modcm_freeStruct(arg1);
        
        {
            SucceedTP * resultobj = (SucceedTP *) malloc(sizeof(SucceedTP));
            memmove(resultobj, &result, sizeof(SucceedTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_SucceedTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_freeArrayStruct) {
    {
        ObservationArrayTP arg1 ;
        SucceedTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_freeArrayStruct(obs);");
        }
        {
            ObservationArrayTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ObservationArrayTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_freeArrayStruct. Expected _p_ObservationArrayTP");
            }
            arg1 = *argp;
        }
        result = modcm_freeArrayStruct(arg1);
        
        {
            SucceedTP * resultobj = (SucceedTP *) malloc(sizeof(SucceedTP));
            memmove(resultobj, &result, sizeof(SucceedTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_SucceedTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_getId) {
    {
        ModcObsTP arg1 ;
        IdTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_getId(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_getId. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = (IdTP)modcm_getId(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_getRa) {
    {
        ModcObsTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_getRa(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_getRa. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = (double)modcm_getRa(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_getDec) {
    {
        ModcObsTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_getDec(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_getDec. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = (double)modcm_getDec(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_getEpoch) {
    {
        ModcObsTP arg1 ;
        MjdTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_getEpoch(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_getEpoch. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = (MjdTP)modcm_getEpoch(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_getSurveyMode) {
    {
        ModcObsTP arg1 ;
        SurveyTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_getSurveyMode(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_getSurveyMode. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = (SurveyTP)modcm_getSurveyMode(arg1);
        
        ST(argvi) = sv_newmortal();
        if (result) {
            sv_setpv((SV*)ST(argvi++), (char *) result);
        } else {
            sv_setsv((SV*)ST(argvi++), &PL_sv_undef);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_getTimeStop) {
    {
        ModcObsTP arg1 ;
        MjdTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_getTimeStop(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_getTimeStop. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = (MjdTP)modcm_getTimeStop(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_getTimeStart) {
    {
        ModcObsTP arg1 ;
        MjdTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_getTimeStart(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_getTimeStart. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = (MjdTP)modcm_getTimeStart(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_getFilter) {
    {
        ModcObsTP arg1 ;
        FilterTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_getFilter(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_getFilter. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = (FilterTP)modcm_getFilter(arg1);
        
        ST(argvi) = sv_newmortal();
        if (result) {
            sv_setpv((SV*)ST(argvi++), (char *) result);
        } else {
            sv_setsv((SV*)ST(argvi++), &PL_sv_undef);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_getLimitingMag) {
    {
        ModcObsTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_getLimitingMag(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_getLimitingMag. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = (double)modcm_getLimitingMag(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_getRaSigma) {
    {
        ModcObsTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_getRaSigma(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_getRaSigma. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = (double)modcm_getRaSigma(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_getDecSigma) {
    {
        ModcObsTP arg1 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_getDecSigma(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_getDecSigma. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = (double)modcm_getDecSigma(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_getObservatory) {
    {
        ModcObsTP arg1 ;
        ObservatoryTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_getObservatory(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_getObservatory. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = (ObservatoryTP)modcm_getObservatory(arg1);
        
        ST(argvi) = sv_newmortal();
        if (result) {
            sv_setpv((SV*)ST(argvi++), (char *) result);
        } else {
            sv_setsv((SV*)ST(argvi++), &PL_sv_undef);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_getEfficiencies) {
    {
        ModcObsTP arg1 ;
        DoubleArrayTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_getEfficiencies(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_getEfficiencies. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = (DoubleArrayTP)modcm_getEfficiencies(arg1);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_DoubleArrayTP, 0|SWIG_OWNER);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_next) {
    {
        ModcObsTP arg1 ;
        ModcObsTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_next(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_next. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = modcm_next(arg1);
        
        {
            ModcObsTP * resultobj = (ModcObsTP *) malloc(sizeof(ModcObsTP));
            memmove(resultobj, &result, sizeof(ModcObsTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcObsTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_prev) {
    {
        ModcObsTP arg1 ;
        ModcObsTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_prev(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_prev. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = modcm_prev(arg1);
        
        {
            ModcObsTP * resultobj = (ModcObsTP *) malloc(sizeof(ModcObsTP));
            memmove(resultobj, &result, sizeof(ModcObsTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcObsTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_nextDetection) {
    {
        ModcObsTP arg1 ;
        ModcDetTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_nextDetection(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_nextDetection. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = modcm_nextDetection(arg1);
        
        {
            ModcDetTP * resultobj = (ModcDetTP *) malloc(sizeof(ModcDetTP));
            memmove(resultobj, &result, sizeof(ModcDetTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcDetTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_modcm_prevDetection) {
    {
        ModcObsTP arg1 ;
        ModcDetTP result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: modcm_prevDetection(ptr);");
        }
        {
            ModcObsTP * argp;
            if (SWIG_ConvertPtr(ST(0),(void **) &argp, SWIGTYPE_p_ModcObsTP,0) < 0) {
                SWIG_croak("Type error in argument 1 of modcm_prevDetection. Expected _p_ModcObsTP");
            }
            arg1 = *argp;
        }
        result = modcm_prevDetection(arg1);
        
        {
            ModcDetTP * resultobj = (ModcDetTP *) malloc(sizeof(ModcDetTP));
            memmove(resultobj, &result, sizeof(ModcDetTP));
            ST(argvi) = sv_newmortal();
            SWIG_MakePtr(ST(argvi++), (void *) resultobj, SWIGTYPE_p_ModcDetTP, 0|SWIG_OWNER);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}



/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_MjdTP[] = {{"_p_MjdTP", 0, "double *|MjdTP *", 0, 0, 0, 0},{"_p_MjdTP", 0, 0, 0, 0, 0, 0},{"_DoubleArrayTP", 0, 0, 0, 0, 0, 0},{"_p_double", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_SucceedTP[] = {{"_p_SucceedTP", 0, "SucceedTP *", 0, 0, 0, 0},{"_p_SucceedTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_ObservationArrayTP[] = {{"_p_ObservationArrayTP", 0, "ObservationArrayTP *", 0, 0, 0, 0},{"_p_ObservationArrayTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_ModcDetArrayTP[] = {{"_p_ModcDetArrayTP", 0, "ModcDetArrayTP *", 0, 0, 0, 0},{"_p_ModcDetArrayTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__DoubleArrayTP[] = {{"_DoubleArrayTP", 0, "double *|DoubleArrayTP", 0, 0, 0, 0},{"_p_MjdTP", 0, 0, 0, 0, 0, 0},{"_DoubleArrayTP", 0, 0, 0, 0, 0, 0},{"_p_double", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_ModcObsArrayTP[] = {{"_p_ModcObsArrayTP", 0, "ModcObsArrayTP *", 0, 0, 0, 0},{"_p_ModcObsArrayTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_IdTP[] = {{"_p_IdTP", 0, "long *|IdTP *", 0, 0, 0, 0},{"_p_IdTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_BoolTP[] = {{"_p_BoolTP", 0, "int *|BoolTP *", 0, 0, 0, 0},{"_p_BoolTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_double[] = {{"_p_double", 0, "double *", 0, 0, 0, 0},{"_p_MjdTP", 0, 0, 0, 0, 0, 0},{"_DoubleArrayTP", 0, 0, 0, 0, 0, 0},{"_p_double", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_ModcObsTP[] = {{"_p_ModcObsTP", 0, "ModcObsTP *", 0, 0, 0, 0},{"_p_ModcObsTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_ObservationTP[] = {{"_p_ObservationTP", 0, "ObservationTP *", 0, 0, 0, 0},{"_p_ObservationTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_ModcDetTP[] = {{"_p_ModcDetTP", 0, "ModcDetTP *", 0, 0, 0, 0},{"_p_ModcDetTP", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_MjdTP, 
_swigt__p_SucceedTP, 
_swigt__p_ObservationArrayTP, 
_swigt__p_ModcDetArrayTP, 
_swigt__DoubleArrayTP, 
_swigt__p_ModcObsArrayTP, 
_swigt__p_IdTP, 
_swigt__p_BoolTP, 
_swigt__p_double, 
_swigt__p_ModcObsTP, 
_swigt__p_ObservationTP, 
_swigt__p_ModcDetTP, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_constant_info swig_constants[] = {
{0,0,0,0,0,0}
};
#ifdef __cplusplus
}
#endif
static swig_variable_info swig_variables[] = {
{0,0,0,0}
};
static swig_command_info swig_commands[] = {
{"PS::MOPS::DB::Observationc::new_doubleArray", _wrap_new_doubleArray},
{"PS::MOPS::DB::Observationc::delete_doubleArray", _wrap_delete_doubleArray},
{"PS::MOPS::DB::Observationc::doubleArray_getitem", _wrap_doubleArray_getitem},
{"PS::MOPS::DB::Observationc::doubleArray_setitem", _wrap_doubleArray_setitem},
{"PS::MOPS::DB::Observationc::modcm_toStruct", _wrap_modcm_toStruct},
{"PS::MOPS::DB::Observationc::modcm_toStructArray", _wrap_modcm_toStructArray},
{"PS::MOPS::DB::Observationc::modcm_getCount", _wrap_modcm_getCount},
{"PS::MOPS::DB::Observationc::modcm_getDetectionCount", _wrap_modcm_getDetectionCount},
{"PS::MOPS::DB::Observationc::modcm_getDetections", _wrap_modcm_getDetections},
{"PS::MOPS::DB::Observationc::modcm_create", _wrap_modcm_create},
{"PS::MOPS::DB::Observationc::modcm_retrieve", _wrap_modcm_retrieve},
{"PS::MOPS::DB::Observationc::modcm_retrieveByValue", _wrap_modcm_retrieveByValue},
{"PS::MOPS::DB::Observationc::modcm_insert", _wrap_modcm_insert},
{"PS::MOPS::DB::Observationc::modcm_insertByValue", _wrap_modcm_insertByValue},
{"PS::MOPS::DB::Observationc::modcm_addDetections", _wrap_modcm_addDetections},
{"PS::MOPS::DB::Observationc::modcm_delete", _wrap_modcm_delete},
{"PS::MOPS::DB::Observationc::modcm_free", _wrap_modcm_free},
{"PS::MOPS::DB::Observationc::modcm_freeArray", _wrap_modcm_freeArray},
{"PS::MOPS::DB::Observationc::modcm_freeStruct", _wrap_modcm_freeStruct},
{"PS::MOPS::DB::Observationc::modcm_freeArrayStruct", _wrap_modcm_freeArrayStruct},
{"PS::MOPS::DB::Observationc::modcm_getId", _wrap_modcm_getId},
{"PS::MOPS::DB::Observationc::modcm_getRa", _wrap_modcm_getRa},
{"PS::MOPS::DB::Observationc::modcm_getDec", _wrap_modcm_getDec},
{"PS::MOPS::DB::Observationc::modcm_getEpoch", _wrap_modcm_getEpoch},
{"PS::MOPS::DB::Observationc::modcm_getSurveyMode", _wrap_modcm_getSurveyMode},
{"PS::MOPS::DB::Observationc::modcm_getTimeStop", _wrap_modcm_getTimeStop},
{"PS::MOPS::DB::Observationc::modcm_getTimeStart", _wrap_modcm_getTimeStart},
{"PS::MOPS::DB::Observationc::modcm_getFilter", _wrap_modcm_getFilter},
{"PS::MOPS::DB::Observationc::modcm_getLimitingMag", _wrap_modcm_getLimitingMag},
{"PS::MOPS::DB::Observationc::modcm_getRaSigma", _wrap_modcm_getRaSigma},
{"PS::MOPS::DB::Observationc::modcm_getDecSigma", _wrap_modcm_getDecSigma},
{"PS::MOPS::DB::Observationc::modcm_getObservatory", _wrap_modcm_getObservatory},
{"PS::MOPS::DB::Observationc::modcm_getEfficiencies", _wrap_modcm_getEfficiencies},
{"PS::MOPS::DB::Observationc::modcm_next", _wrap_modcm_next},
{"PS::MOPS::DB::Observationc::modcm_prev", _wrap_modcm_prev},
{"PS::MOPS::DB::Observationc::modcm_nextDetection", _wrap_modcm_nextDetection},
{"PS::MOPS::DB::Observationc::modcm_prevDetection", _wrap_modcm_prevDetection},
{0,0}
};

#ifdef __cplusplus
extern "C"
#endif

XS(SWIG_init) {
    dXSARGS;
    int i;
    static int _init = 0;
    if (!_init) {
        SWIG_Perl_LookupTypePointer();
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }	
        _init = 1;
    }
    
    /* Install commands */
    for (i = 0; swig_commands[i].name; i++) {
        newXS((char*) swig_commands[i].name,swig_commands[i].wrapper, (char*)__FILE__);
    }
    
    /* Install variables */
    for (i = 0; swig_variables[i].name; i++) {
        SV *sv;
        sv = perl_get_sv((char*) swig_variables[i].name, TRUE | 0x2);
        if (swig_variables[i].type) {
            SWIG_MakePtr(sv,(void *)1, *swig_variables[i].type,0);
        } else {
            sv_setiv(sv,(IV) 0);
        }
        swig_create_magic(sv, (char *) swig_variables[i].name, swig_variables[i].set, swig_variables[i].get); 
    }
    
    /* Install constant */
    for (i = 0; swig_constants[i].type; i++) {
        SV *sv;
        sv = perl_get_sv((char*)swig_constants[i].name, TRUE | 0x2);
        switch(swig_constants[i].type) {
            case SWIG_INT:
            sv_setiv(sv, (IV) swig_constants[i].lvalue);
            break;
            case SWIG_FLOAT:
            sv_setnv(sv, (double) swig_constants[i].dvalue);
            break;
            case SWIG_STRING:
            sv_setpv(sv, (char *) swig_constants[i].pvalue);
            break;
            case SWIG_POINTER:
            SWIG_MakePtr(sv, swig_constants[i].pvalue, *(swig_constants[i].ptype),0);
            break;
            case SWIG_BINARY:
            SWIG_MakePackedObj(sv, swig_constants[i].pvalue, swig_constants[i].lvalue, *(swig_constants[i].ptype));
            break;
            default:
            break;
        }
        SvREADONLY_on(sv);
    }
    
    ST(0) = &PL_sv_yes;
    XSRETURN(1);
}

