build: setup.py
	# python setup.py build && python setup.py test && python setup.py install --home=${MOPS_HOME}
	python setup.py build

install: 
	python setup.py build && python setup.py install --home=${MOPS_HOME}

