# Makefile for dirlib ~/g/detectionproximity
# Created by jkubica on:  Tue Apr 19 16:06:24 EDT 2005

here		= detectionproximity

includes	= detectprox.h

sources		= detectprox.c

private_sources = 

# Warning: Make sure the siblings are ordered so that, for example, if
#          a depends on b then b is to the right of a in the following list

siblings	= linkTracklets autonutils

t:=debug
include ../gmake-magic/Make.common

