# Makefile for dirlib ~/g/utils
# Created by awm on:  Sat Feb 28 09:46:50 EST 1998
# Modified by sir on: Thu Jun  8 14:37:59 EDT 2000

here		= autonutils

includes	= standard.h imat.h hash.h genarray.h command.h \
                  amut.h ammarep.h amma.h amiv.h amdyv.h backtrace.h \
                  amdym.h amdmex.h ambs.h amar.h \
                  am_time.h am_time_private.h \
                  utils.h am_string.h am_string_array.h am_file.h \
		  amdyv_array.h amma_type.h amma_check.h \
		  auton_sf.h param.h internal_state.h \
		  namer.h geometry.h eq_solvers.h

sources		= imat.c hash.c genarray.c command.c \
                  ammarep.c amma.c amiv.c amdyv.c \
                  amdym.c amdmex.c ambs.c amar.c backtrace.c \
                  am_time.c am_string.c am_string_array.c am_file.c \
		  amdyv_array.c amma_check.c \
		  auton_sf.c param.c internal_state.c \
		  namer.c geometry.c eq_solvers.c

private_sources =

siblings	= 

t:=debug
include ../gmake-magic/Make.common
