# Makefile for dirlib ~/g/orboccur
# Created by jkubica on:  Tue Nov 23 11:17:50 EST 2004

here		= fieldProximity

includes	= occ_tree_funs.h pw_linear.h pw_tree.h

sources		= occ_tree_funs.c pw_linear.c pw_tree.c

private_sources = 

# Warning: Make sure the siblings are ordered so that, for example, if
#          a depends on b then b is to the right of a in the following list

siblings	= linkTracklets autonutils

t:=debug
include ../gmake-magic/Make.common

